/**
 * Npcf_AMPolicyAuthorization Service API
 * PCF Access and Mobility Policy Authorization Service. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AmEventsSubscDataRm.h
 *
 * This data type is defined in the same way as the AmEventsSubscData but with
 * the OpenAPI nullable property set to true.
 */

#ifndef AmEventsSubscDataRm_H_
#define AmEventsSubscDataRm_H_

#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// This data type is defined in the same way as the AmEventsSubscData but with
/// the OpenAPI nullable property set to true.
/// </summary>
class AmEventsSubscDataRm {
public:
  AmEventsSubscDataRm();
  virtual ~AmEventsSubscDataRm();

  void validate();

  /////////////////////////////////////////////
  /// AmEventsSubscDataRm members

  /// <summary>
  /// String providing an URI formatted according to RFC 3986
  /// </summary>
  std::string getEventNotifUri() const;
  void setEventNotifUri(std::string const &value);
  bool eventNotifUriIsSet() const;
  void unsetEventNotifUri();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> &getEvents();
  void setEvents(std::vector<std::string> const &value);
  bool eventsIsSet() const;
  void unsetEvents();

  friend void to_json(nlohmann::json &j, const AmEventsSubscDataRm &o);
  friend void from_json(const nlohmann::json &j, AmEventsSubscDataRm &o);

protected:
  std::string m_EventNotifUri;
  bool m_EventNotifUriIsSet;
  std::vector<std::string> m_Events;
  bool m_EventsIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* AmEventsSubscDataRm_H_ */
