/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AmfStatusChangeNotification.h
 *
 * Data within an AMF Status Change Notification request
 */

#ifndef AmfStatusChangeNotification_H_
#define AmfStatusChangeNotification_H_

#include "AmfStatusInfo.h"
#include <nlohmann/json.hpp>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Data within an AMF Status Change Notification request
/// </summary>
class AmfStatusChangeNotification {
public:
  AmfStatusChangeNotification();
  virtual ~AmfStatusChangeNotification();

  void validate();

  /////////////////////////////////////////////
  /// AmfStatusChangeNotification members

  /// <summary>
  ///
  /// </summary>
  std::vector<AmfStatusInfo> &getAmfStatusInfoList();
  void setAmfStatusInfoList(std::vector<AmfStatusInfo> const &value);

  friend void to_json(nlohmann::json &j, const AmfStatusChangeNotification &o);
  friend void from_json(const nlohmann::json &j,
                        AmfStatusChangeNotification &o);

protected:
  std::vector<AmfStatusInfo> m_AmfStatusInfoList;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* AmfStatusChangeNotification_H_ */
