/**
 * N32 Handshake API
 * N32-c Handshake Service.  © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ApiSignature.h
 *
 * API URI of the service operation
 */

#ifndef ApiSignature_H_
#define ApiSignature_H_

#include "CallbackName.h"
#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// API URI of the service operation
/// </summary>
class ApiSignature {
public:
  ApiSignature();
  virtual ~ApiSignature();

  void validate();

  /////////////////////////////////////////////
  /// ApiSignature members

  /// <summary>
  ///
  /// </summary>
  std::string getCallbackType() const;
  void setCallbackType(std::string const &value);

  friend void to_json(nlohmann::json &j, const ApiSignature &o);
  friend void from_json(const nlohmann::json &j, ApiSignature &o);

protected:
  std::string m_CallbackType;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* ApiSignature_H_ */
