/**
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 3.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ChargingNotifyResponse.h
 *
 *
 */

#ifndef ChargingNotifyResponse_H_
#define ChargingNotifyResponse_H_

#include "InvocationResult.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class ChargingNotifyResponse {
public:
  ChargingNotifyResponse();
  virtual ~ChargingNotifyResponse();

  void validate();

  /////////////////////////////////////////////
  /// ChargingNotifyResponse members

  /// <summary>
  ///
  /// </summary>
  InvocationResult getInvocationResult() const;
  void setInvocationResult(InvocationResult const &value);
  bool invocationResultIsSet() const;
  void unsetInvocationResult();

  friend void to_json(nlohmann::json &j, const ChargingNotifyResponse &o);
  friend void from_json(const nlohmann::json &j, ChargingNotifyResponse &o);

protected:
  InvocationResult m_InvocationResult;
  bool m_InvocationResultIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* ChargingNotifyResponse_H_ */
