/**
 * M1_PolicyTemplatesProvisioning
 * 5GMS AF M1 Policy Templates Provisioning API © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ChargingSpecification.h
 *
 *
 */

#ifndef ChargingSpecification_H_
#define ChargingSpecification_H_

#include "SponsoringStatus.h"
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class ChargingSpecification {
public:
  ChargingSpecification();
  virtual ~ChargingSpecification();

  void validate();

  /////////////////////////////////////////////
  /// ChargingSpecification members

  /// <summary>
  ///
  /// </summary>
  std::string getSponId() const;
  void setSponId(std::string const &value);
  bool sponIdIsSet() const;
  void unsetSponId();
  /// <summary>
  ///
  /// </summary>
  SponsoringStatus getSponStatus() const;
  void setSponStatus(SponsoringStatus const &value);
  bool sponStatusIsSet() const;
  void unsetSponStatus();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> &getGpsi();
  void setGpsi(std::vector<std::string> const &value);
  bool gpsiIsSet() const;
  void unsetGpsi();

  friend void to_json(nlohmann::json &j, const ChargingSpecification &o);
  friend void from_json(const nlohmann::json &j, ChargingSpecification &o);

protected:
  std::string m_SponId;
  bool m_SponIdIsSet;
  SponsoringStatus m_SponStatus;
  bool m_SponStatusIsSet;
  std::vector<std::string> m_Gpsi;
  bool m_GpsiIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* ChargingSpecification_H_ */
