/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * CoreNetworkTypeRm.h
 *
 * It contains the Core Network type 5GC or EPC but with the OpenAPI
 * \&quot;nullable&#x3D; true\&quot; property.
 */

#ifndef CoreNetworkTypeRm_H_
#define CoreNetworkTypeRm_H_

#include "CoreNetworkType.h"
#include "NullValue.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// It contains the Core Network type 5GC or EPC but with the OpenAPI
/// \&quot;nullable&#x3D; true\&quot; property.
/// </summary>
class CoreNetworkTypeRm {
public:
  CoreNetworkTypeRm();
  virtual ~CoreNetworkTypeRm();

  void validate();

  /////////////////////////////////////////////
  /// CoreNetworkTypeRm members

  friend void to_json(nlohmann::json &j, const CoreNetworkTypeRm &o);
  friend void from_json(const nlohmann::json &j, CoreNetworkTypeRm &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* CoreNetworkTypeRm_H_ */
