/**
 * SS_NetworkResourceAdaptation
 * SS Network Resource Adaptation Service. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * DeliveryMode.h
 *
 * Possible values are - UNICAST: Unicast delivery. - MULTICAST: Multicast
 * delivery.
 */

#ifndef DeliveryMode_H_
#define DeliveryMode_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Possible values are - UNICAST: Unicast delivery. - MULTICAST: Multicast
/// delivery.
/// </summary>
class DeliveryMode {
public:
  DeliveryMode();
  virtual ~DeliveryMode();

  void validate();

  /////////////////////////////////////////////
  /// DeliveryMode members

  friend void to_json(nlohmann::json &j, const DeliveryMode &o);
  friend void from_json(const nlohmann::json &j, DeliveryMode &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* DeliveryMode_H_ */
