/**
 * 3gpp-device-triggering
 * API for device trigger. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "DeviceTriggeringDeliveryReportNotification.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

DeviceTriggeringDeliveryReportNotification::
    DeviceTriggeringDeliveryReportNotification() {
  m_Transaction = "";
}

DeviceTriggeringDeliveryReportNotification::
    ~DeviceTriggeringDeliveryReportNotification() {}

void DeviceTriggeringDeliveryReportNotification::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j,
             const DeviceTriggeringDeliveryReportNotification &o) {
  j = nlohmann::json();
  j["transaction"] = o.m_Transaction;
  j["result"] = o.m_Result;
}

void from_json(const nlohmann::json &j,
               DeviceTriggeringDeliveryReportNotification &o) {
  j.at("transaction").get_to(o.m_Transaction);
  j.at("result").get_to(o.m_Result);
}

std::string DeviceTriggeringDeliveryReportNotification::getTransaction() const {
  return m_Transaction;
}
void DeviceTriggeringDeliveryReportNotification::setTransaction(
    std::string const &value) {
  m_Transaction = value;
}
DeliveryResult DeviceTriggeringDeliveryReportNotification::getResult() const {
  return m_Result;
}
void DeviceTriggeringDeliveryReportNotification::setResult(
    DeliveryResult const &value) {
  m_Result = value;
}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
