/**
 * VAE_DynamicGroup
 * VAE_Dynamic_Group Service © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "DynamicGroupNotification.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

DynamicGroupNotification::DynamicGroupNotification() {
  m_ResourceUri = "";
  m_JoinedUeIdsIsSet = false;
  m_LeftUeIdsIsSet = false;
}

DynamicGroupNotification::~DynamicGroupNotification() {}

void DynamicGroupNotification::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const DynamicGroupNotification &o) {
  j = nlohmann::json();
  j["resourceUri"] = o.m_ResourceUri;
  if (o.joinedUeIdsIsSet() || !o.m_JoinedUeIds.empty())
    j["joinedUeIds"] = o.m_JoinedUeIds;
  if (o.leftUeIdsIsSet() || !o.m_LeftUeIds.empty())
    j["leftUeIds"] = o.m_LeftUeIds;
}

void from_json(const nlohmann::json &j, DynamicGroupNotification &o) {
  j.at("resourceUri").get_to(o.m_ResourceUri);
  if (j.find("joinedUeIds") != j.end()) {
    j.at("joinedUeIds").get_to(o.m_JoinedUeIds);
    o.m_JoinedUeIdsIsSet = true;
  }
  if (j.find("leftUeIds") != j.end()) {
    j.at("leftUeIds").get_to(o.m_LeftUeIds);
    o.m_LeftUeIdsIsSet = true;
  }
}

std::string DynamicGroupNotification::getResourceUri() const {
  return m_ResourceUri;
}
void DynamicGroupNotification::setResourceUri(std::string const &value) {
  m_ResourceUri = value;
}
std::vector<std::string> &DynamicGroupNotification::getJoinedUeIds() {
  return m_JoinedUeIds;
}
void DynamicGroupNotification::setJoinedUeIds(
    std::vector<std::string> const &value) {
  m_JoinedUeIds = value;
  m_JoinedUeIdsIsSet = true;
}
bool DynamicGroupNotification::joinedUeIdsIsSet() const {
  return m_JoinedUeIdsIsSet;
}
void DynamicGroupNotification::unsetJoinedUeIds() {
  m_JoinedUeIdsIsSet = false;
}
std::vector<std::string> &DynamicGroupNotification::getLeftUeIds() {
  return m_LeftUeIds;
}
void DynamicGroupNotification::setLeftUeIds(
    std::vector<std::string> const &value) {
  m_LeftUeIds = value;
  m_LeftUeIdsIsSet = true;
}
bool DynamicGroupNotification::leftUeIdsIsSet() const {
  return m_LeftUeIdsIsSet;
}
void DynamicGroupNotification::unsetLeftUeIds() { m_LeftUeIdsIsSet = false; }

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
