/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ExpectedAnalyticsType.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

ExpectedAnalyticsType::ExpectedAnalyticsType() {}

ExpectedAnalyticsType::~ExpectedAnalyticsType() {}

void ExpectedAnalyticsType::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const ExpectedAnalyticsType &o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json &j, ExpectedAnalyticsType &o) {}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
