/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ExtendedProblemDetails_allOf.h
 *
 *
 */

#ifndef ExtendedProblemDetails_allOf_H_
#define ExtendedProblemDetails_allOf_H_

#include "AcceptableServiceInfo.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class ExtendedProblemDetails_allOf {
public:
  ExtendedProblemDetails_allOf();
  virtual ~ExtendedProblemDetails_allOf();

  void validate();

  /////////////////////////////////////////////
  /// ExtendedProblemDetails_allOf members

  /// <summary>
  ///
  /// </summary>
  AcceptableServiceInfo getAcceptableServInfo() const;
  void setAcceptableServInfo(AcceptableServiceInfo const &value);
  bool acceptableServInfoIsSet() const;
  void unsetAcceptableServInfo();

  friend void to_json(nlohmann::json &j, const ExtendedProblemDetails_allOf &o);
  friend void from_json(const nlohmann::json &j,
                        ExtendedProblemDetails_allOf &o);

protected:
  AcceptableServiceInfo m_AcceptableServInfo;
  bool m_AcceptableServInfoIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* ExtendedProblemDetails_allOf_H_ */
