/**
 * LMF Location
 * LMF Location Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * HorizontalVelocity.h
 *
 * Horizontal velocity.
 */

#ifndef HorizontalVelocity_H_
#define HorizontalVelocity_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Horizontal velocity.
/// </summary>
class HorizontalVelocity {
public:
  HorizontalVelocity();
  virtual ~HorizontalVelocity();

  void validate();

  /////////////////////////////////////////////
  /// HorizontalVelocity members

  /// <summary>
  /// Indicates value of horizontal speed.
  /// </summary>
  float getHSpeed() const;
  void setHSpeed(float const value);
  /// <summary>
  /// Indicates value of angle.
  /// </summary>
  int32_t getBearing() const;
  void setBearing(int32_t const value);

  friend void to_json(nlohmann::json &j, const HorizontalVelocity &o);
  friend void from_json(const nlohmann::json &j, HorizontalVelocity &o);

protected:
  float m_HSpeed;

  int32_t m_Bearing;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* HorizontalVelocity_H_ */
