/**
 * Nhss_imsSDM
 * Nhss Subscriber Data Management Service for IMS. © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Ifc.h
 *
 *
 */

#ifndef Ifc_H_
#define Ifc_H_

#include "ApplicationServer.h"
#include "TriggerPoint.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class Ifc {
public:
  Ifc();
  virtual ~Ifc();

  void validate();

  /////////////////////////////////////////////
  /// Ifc members

  /// <summary>
  ///
  /// </summary>
  int32_t getPriority() const;
  void setPriority(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  TriggerPoint getTrigger() const;
  void setTrigger(TriggerPoint const &value);
  bool triggerIsSet() const;
  void unsetTrigger();
  /// <summary>
  ///
  /// </summary>
  ApplicationServer getAppServer() const;
  void setAppServer(ApplicationServer const &value);

  friend void to_json(nlohmann::json &j, const Ifc &o);
  friend void from_json(const nlohmann::json &j, Ifc &o);

protected:
  int32_t m_Priority;

  TriggerPoint m_Trigger;
  bool m_TriggerIsSet;
  ApplicationServer m_AppServer;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* Ifc_H_ */
