/**
 * Nhss_imsSDM
 * Nhss Subscriber Data Management Service for IMS. © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ImsServiceProfile.h
 *
 *
 */

#ifndef ImsServiceProfile_H_
#define ImsServiceProfile_H_

#include "Ifcs.h"
#include "PublicIdentifier.h"
#include <nlohmann/json.hpp>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class ImsServiceProfile {
public:
  ImsServiceProfile();
  virtual ~ImsServiceProfile();

  void validate();

  /////////////////////////////////////////////
  /// ImsServiceProfile members

  /// <summary>
  ///
  /// </summary>
  std::vector<PublicIdentifier> &getPublicIdentifierList();
  void setPublicIdentifierList(std::vector<PublicIdentifier> const &value);
  /// <summary>
  ///
  /// </summary>
  Ifcs getIfcs() const;
  void setIfcs(Ifcs const &value);
  bool ifcsIsSet() const;
  void unsetIfcs();

  friend void to_json(nlohmann::json &j, const ImsServiceProfile &o);
  friend void from_json(const nlohmann::json &j, ImsServiceProfile &o);

protected:
  std::vector<PublicIdentifier> m_PublicIdentifierList;

  Ifcs m_Ifcs;
  bool m_IfcsIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* ImsServiceProfile_H_ */
