/**
 * Nhss_imsUEAU
 * Nhss UE Authentication Service for IMS. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * IpAddress.h
 *
 *
 */

#ifndef IpAddress_H_
#define IpAddress_H_

#include "Ipv6Addr.h"
#include "Ipv6Prefix.h"
#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class IpAddress {
public:
  IpAddress();
  virtual ~IpAddress();

  void validate();

  /////////////////////////////////////////////
  /// IpAddress members

  /// <summary>
  /// String identifying a IPv4 address formatted in the \&quot;dotted
  /// decimal\&quot; notation as defined in RFC 1166.
  /// </summary>
  std::string getIpv4Addr() const;
  void setIpv4Addr(std::string const &value);
  bool ipv4AddrIsSet() const;
  void unsetIpv4Addr();
  /// <summary>
  ///
  /// </summary>
  Ipv6Addr getIpv6Addr() const;
  void setIpv6Addr(Ipv6Addr const &value);
  bool ipv6AddrIsSet() const;
  void unsetIpv6Addr();
  /// <summary>
  ///
  /// </summary>
  Ipv6Prefix getIpv6Prefix() const;
  void setIpv6Prefix(Ipv6Prefix const &value);
  bool ipv6PrefixIsSet() const;
  void unsetIpv6Prefix();

  friend void to_json(nlohmann::json &j, const IpAddress &o);
  friend void from_json(const nlohmann::json &j, IpAddress &o);

protected:
  std::string m_Ipv4Addr;
  bool m_Ipv4AddrIsSet;
  Ipv6Addr m_Ipv6Addr;
  bool m_Ipv6AddrIsSet;
  Ipv6Prefix m_Ipv6Prefix;
  bool m_Ipv6PrefixIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* IpAddress_H_ */
