/**
 * Nhss_imsSDM
 * Nhss Subscriber Data Management Service for IMS. © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * IpSmGwAddress.h
 *
 *
 */

#ifndef IpSmGwAddress_H_
#define IpSmGwAddress_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class IpSmGwAddress {
public:
  IpSmGwAddress();
  virtual ~IpSmGwAddress();

  void validate();

  /////////////////////////////////////////////
  /// IpSmGwAddress members

  /// <summary>
  ///
  /// </summary>
  std::string getIpSmGwNumber() const;
  void setIpSmGwNumber(std::string const &value);
  /// <summary>
  /// string containing an FQDN or realm as defined in RFC 6733.
  /// </summary>
  std::string getIpSmGwDiaUri() const;
  void setIpSmGwDiaUri(std::string const &value);
  bool ipSmGwDiaUriIsSet() const;
  void unsetIpSmGwDiaUri();
  /// <summary>
  /// string containing an FQDN or realm as defined in RFC 6733.
  /// </summary>
  std::string getIpSmGwDiaRealm() const;
  void setIpSmGwDiaRealm(std::string const &value);
  bool ipSmGwDiaRealmIsSet() const;
  void unsetIpSmGwDiaRealm();

  friend void to_json(nlohmann::json &j, const IpSmGwAddress &o);
  friend void from_json(const nlohmann::json &j, IpSmGwAddress &o);

protected:
  std::string m_IpSmGwNumber;

  std::string m_IpSmGwDiaUri;
  bool m_IpSmGwDiaUriIsSet;
  std::string m_IpSmGwDiaRealm;
  bool m_IpSmGwDiaRealmIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* IpSmGwAddress_H_ */
