/**
 * Nudsf_DataRepository
 * Nudsf Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * KeyType.h
 *
 * Represents the type of a key.
 */

#ifndef KeyType_H_
#define KeyType_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Represents the type of a key.
/// </summary>
class KeyType {
public:
  KeyType();
  virtual ~KeyType();

  void validate();

  /////////////////////////////////////////////
  /// KeyType members

  friend void to_json(nlohmann::json &j, const KeyType &o);
  friend void from_json(const nlohmann::json &j, KeyType &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* KeyType_H_ */
