/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * LadnInfo.h
 *
 * LADN Information
 */

#ifndef LadnInfo_H_
#define LadnInfo_H_

#include "PresenceState.h"
#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// LADN Information
/// </summary>
class LadnInfo {
public:
  LadnInfo();
  virtual ~LadnInfo();

  void validate();

  /////////////////////////////////////////////
  /// LadnInfo members

  /// <summary>
  ///
  /// </summary>
  std::string getLadn() const;
  void setLadn(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  PresenceState getPresence() const;
  void setPresence(PresenceState const &value);
  bool presenceIsSet() const;
  void unsetPresence();

  friend void to_json(nlohmann::json &j, const LadnInfo &o);
  friend void from_json(const nlohmann::json &j, LadnInfo &o);

protected:
  std::string m_Ladn;

  PresenceState m_Presence;
  bool m_PresenceIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* LadnInfo_H_ */
