/**
 * Namf_Location
 * AMF Location Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * LocationEvent.h
 *
 * Type of events initiating location procedures
 */

#ifndef LocationEvent_H_
#define LocationEvent_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Type of events initiating location procedures
/// </summary>
class LocationEvent {
public:
  LocationEvent();
  virtual ~LocationEvent();

  void validate();

  /////////////////////////////////////////////
  /// LocationEvent members

  friend void to_json(nlohmann::json &j, const LocationEvent &o);
  friend void from_json(const nlohmann::json &j, LocationEvent &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* LocationEvent_H_ */
