/**
 * LMF Location
 * LMF Location Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Local2dPointUncertaintyEllipse.h
 *
 * Local 2D point with uncertainty ellipse
 */

#ifndef Local2dPointUncertaintyEllipse_H_
#define Local2dPointUncertaintyEllipse_H_

#include "GADShape.h"
#include "Local2dPointUncertaintyEllipse_allOf.h"
#include "LocalOrigin.h"
#include "RelativeCartesianLocation.h"
#include "SupportedGADShapes.h"
#include "UncertaintyEllipse.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Local 2D point with uncertainty ellipse
/// </summary>
class Local2dPointUncertaintyEllipse {
public:
  Local2dPointUncertaintyEllipse();
  virtual ~Local2dPointUncertaintyEllipse();

  void validate();

  /////////////////////////////////////////////
  /// Local2dPointUncertaintyEllipse members

  /// <summary>
  ///
  /// </summary>
  SupportedGADShapes getShape() const;
  void setShape(SupportedGADShapes const &value);
  /// <summary>
  ///
  /// </summary>
  LocalOrigin getLocalOrigin() const;
  void setLocalOrigin(LocalOrigin const &value);
  /// <summary>
  ///
  /// </summary>
  RelativeCartesianLocation getPoint() const;
  void setPoint(RelativeCartesianLocation const &value);
  /// <summary>
  ///
  /// </summary>
  UncertaintyEllipse getUncertaintyEllipse() const;
  void setUncertaintyEllipse(UncertaintyEllipse const &value);
  /// <summary>
  /// Indicates value of confidence.
  /// </summary>
  int32_t getConfidence() const;
  void setConfidence(int32_t const value);

  friend void to_json(nlohmann::json &j,
                      const Local2dPointUncertaintyEllipse &o);
  friend void from_json(const nlohmann::json &j,
                        Local2dPointUncertaintyEllipse &o);

protected:
  SupportedGADShapes m_Shape;

  LocalOrigin m_LocalOrigin;

  RelativeCartesianLocation m_Point;

  UncertaintyEllipse m_UncertaintyEllipse;

  int32_t m_Confidence;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* Local2dPointUncertaintyEllipse_H_ */
