/**
 * N5g-ddnmf_Discovery API
 * N5g-ddnmf_Discovery Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * MonitorAuthDataForRestricted.h
 *
 * Represents the obtained Announce Authorize Data for restricted discovery for
 * a UE
 */

#ifndef MonitorAuthDataForRestricted_H_
#define MonitorAuthDataForRestricted_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Represents the obtained Announce Authorize Data for restricted discovery for
/// a UE
/// </summary>
class MonitorAuthDataForRestricted {
public:
  MonitorAuthDataForRestricted();
  virtual ~MonitorAuthDataForRestricted();

  void validate();

  /////////////////////////////////////////////
  /// MonitorAuthDataForRestricted members

  /// <summary>
  /// Contains the ProSe Restricted Code.
  /// </summary>
  std::string getProseRestrictedCode() const;
  void setProseRestrictedCode(std::string const &value);
  /// <summary>
  /// string with format \&quot;date-time\&quot; as defined in OpenAPI.
  /// </summary>
  std::string getValidityTime() const;
  void setValidityTime(std::string const &value);

  friend void to_json(nlohmann::json &j, const MonitorAuthDataForRestricted &o);
  friend void from_json(const nlohmann::json &j,
                        MonitorAuthDataForRestricted &o);

protected:
  std::string m_ProseRestrictedCode;

  std::string m_ValidityTime;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* MonitorAuthDataForRestricted_H_ */
