/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "MonitoringEvent.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

MonitoringEvent::MonitoringEvent() { m_RevokedCauseIsSet = false; }

MonitoringEvent::~MonitoringEvent() {}

void MonitoringEvent::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const MonitoringEvent &o) {
  j = nlohmann::json();
  j["eventType"] = o.m_EventType;
  if (o.revokedCauseIsSet())
    j["revokedCause"] = o.m_RevokedCause;
}

void from_json(const nlohmann::json &j, MonitoringEvent &o) {
  j.at("eventType").get_to(o.m_EventType);
  if (j.find("revokedCause") != j.end()) {
    j.at("revokedCause").get_to(o.m_RevokedCause);
    o.m_RevokedCauseIsSet = true;
  }
}

EventType MonitoringEvent::getEventType() const { return m_EventType; }
void MonitoringEvent::setEventType(EventType const &value) {
  m_EventType = value;
}
RevokedCause MonitoringEvent::getRevokedCause() const { return m_RevokedCause; }
void MonitoringEvent::setRevokedCause(RevokedCause const &value) {
  m_RevokedCause = value;
  m_RevokedCauseIsSet = true;
}
bool MonitoringEvent::revokedCauseIsSet() const { return m_RevokedCauseIsSet; }
void MonitoringEvent::unsetRevokedCause() { m_RevokedCauseIsSet = false; }

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
