/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * N1N2MessageTransferRspData.h
 *
 * Data within a N1/N2 message transfer response
 */

#ifndef N1N2MessageTransferRspData_H_
#define N1N2MessageTransferRspData_H_

#include "N1N2MessageTransferCause.h"
#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Data within a N1/N2 message transfer response
/// </summary>
class N1N2MessageTransferRspData {
public:
  N1N2MessageTransferRspData();
  virtual ~N1N2MessageTransferRspData();

  void validate();

  /////////////////////////////////////////////
  /// N1N2MessageTransferRspData members

  /// <summary>
  ///
  /// </summary>
  N1N2MessageTransferCause getCause() const;
  void setCause(N1N2MessageTransferCause const &value);
  /// <summary>
  /// A string used to indicate the features supported by an API that is used as
  /// defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a
  /// bitmask indicating supported features in hexadecimal representation Each
  /// character in the string shall take a value of \&quot;0\&quot; to
  /// \&quot;9\&quot;, \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to
  /// \&quot;F\&quot; and shall represent the support of 4 features as described
  /// in table 5.2.2-3. The most significant character representing the
  /// highest-numbered features shall appear first in the string, and the
  /// character representing features 1 to 4 shall appear last in the string.
  /// The list of features and their numbering (starting with 1) are defined
  /// separately for each API. If the string contains a lower number of
  /// characters than there are defined features for an API, all features that
  /// would be represented by characters that are not present in the string are
  /// not supported
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const &value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();

  friend void to_json(nlohmann::json &j, const N1N2MessageTransferRspData &o);
  friend void from_json(const nlohmann::json &j, N1N2MessageTransferRspData &o);

protected:
  N1N2MessageTransferCause m_Cause;

  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* N1N2MessageTransferRspData_H_ */
