/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * N4Information.h
 *
 * N4 Information
 */

#ifndef N4Information_H_
#define N4Information_H_

#include "DnaiInformation.h"
#include "N4MessageType.h"
#include "RefToBinaryData.h"
#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// N4 Information
/// </summary>
class N4Information {
public:
  N4Information();
  virtual ~N4Information();

  void validate();

  /////////////////////////////////////////////
  /// N4Information members

  /// <summary>
  ///
  /// </summary>
  N4MessageType getN4MessageType() const;
  void setN4MessageType(N4MessageType const &value);
  /// <summary>
  ///
  /// </summary>
  RefToBinaryData getN4MessagePayload() const;
  void setN4MessagePayload(RefToBinaryData const &value);
  /// <summary>
  ///
  /// </summary>
  DnaiInformation getN4DnaiInfo() const;
  void setN4DnaiInfo(DnaiInformation const &value);
  bool n4DnaiInfoIsSet() const;
  void unsetN4DnaiInfo();
  /// <summary>
  /// String uniquely identifying a NF instance. The format of the NF Instance
  /// ID shall be a Universally Unique Identifier (UUID) version 4, as described
  /// in IETF RFC 4122.
  /// </summary>
  std::string getPsaUpfId() const;
  void setPsaUpfId(std::string const &value);
  bool psaUpfIdIsSet() const;
  void unsetPsaUpfId();

  friend void to_json(nlohmann::json &j, const N4Information &o);
  friend void from_json(const nlohmann::json &j, N4Information &o);

protected:
  N4MessageType m_N4MessageType;

  RefToBinaryData m_N4MessagePayload;

  DnaiInformation m_N4DnaiInfo;
  bool m_N4DnaiInfoIsSet;
  std::string m_PsaUpfId;
  bool m_PsaUpfIdIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* N4Information_H_ */
