/**
 * Nnef_EventExposure
 * NEF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NefEventExposureNotif.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

NefEventExposureNotif::NefEventExposureNotif() { m_NotifId = ""; }

NefEventExposureNotif::~NefEventExposureNotif() {}

void NefEventExposureNotif::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const NefEventExposureNotif &o) {
  j = nlohmann::json();
  j["notifId"] = o.m_NotifId;
  j["eventNotifs"] = o.m_EventNotifs;
}

void from_json(const nlohmann::json &j, NefEventExposureNotif &o) {
  j.at("notifId").get_to(o.m_NotifId);
  j.at("eventNotifs").get_to(o.m_EventNotifs);
}

std::string NefEventExposureNotif::getNotifId() const { return m_NotifId; }
void NefEventExposureNotif::setNotifId(std::string const &value) {
  m_NotifId = value;
}
std::vector<NefEventNotification> &NefEventExposureNotif::getEventNotifs() {
  return m_EventNotifs;
}
void NefEventExposureNotif::setEventNotifs(
    std::vector<NefEventNotification> const &value) {
  m_EventNotifs = value;
}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
