/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NetworkPerfType.h
 *
 * Possible values are   - GNB_ACTIVE_RATIO: Indicates that the network
 * performance requirement is gNodeB active (i.e. up and running) rate.
 * Indicates the ratio of gNB active (i.e. up and running) number to the total
 * number of gNB   - GNB_COMPUTING_USAGE: Indicates gNodeB computing resource
 * usage.   - GNB_MEMORY_USAGE: Indicates gNodeB memory usage.   -
 * GNB_DISK_USAGE: Indicates gNodeB disk usage.   - NUM_OF_UE: Indicates number
 * of UEs.   - SESS_SUCC_RATIO: Indicates ratio of successful setup of PDU
 * sessions to total PDU session setup attempts.   - SESS_SUCC_RATIO: Indicates
 * Ratio of successful handovers to the total handover attempts.
 */

#ifndef NetworkPerfType_H_
#define NetworkPerfType_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Possible values are   - GNB_ACTIVE_RATIO: Indicates that the network
/// performance requirement is gNodeB active (i.e. up and running) rate.
/// Indicates the ratio of gNB active (i.e. up and running) number to the total
/// number of gNB   - GNB_COMPUTING_USAGE: Indicates gNodeB computing resource
/// usage.   - GNB_MEMORY_USAGE: Indicates gNodeB memory usage.   -
/// GNB_DISK_USAGE: Indicates gNodeB disk usage.   - NUM_OF_UE: Indicates number
/// of UEs.   - SESS_SUCC_RATIO: Indicates ratio of successful setup of PDU
/// sessions to total PDU session setup attempts.   - SESS_SUCC_RATIO: Indicates
/// Ratio of successful handovers to the total handover attempts.
/// </summary>
class NetworkPerfType {
public:
  NetworkPerfType();
  virtual ~NetworkPerfType();

  void validate();

  /////////////////////////////////////////////
  /// NetworkPerfType members

  friend void to_json(nlohmann::json &j, const NetworkPerfType &o);
  friend void from_json(const nlohmann::json &j, NetworkPerfType &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* NetworkPerfType_H_ */
