/**
 * NRF NFManagement Service
 * NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NfGroupCond.h
 *
 * Subscription to a set of NFs based on their Group Id
 */

#ifndef NfGroupCond_H_
#define NfGroupCond_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Subscription to a set of NFs based on their Group Id
/// </summary>
class NfGroupCond {
public:
  NfGroupCond();
  virtual ~NfGroupCond();

  void validate();

  /////////////////////////////////////////////
  /// NfGroupCond members

  /// <summary>
  ///
  /// </summary>
  std::string getNfType() const;
  void setNfType(std::string const &value);
  /// <summary>
  /// Identifier of a group of NFs.
  /// </summary>
  std::string getNfGroupId() const;
  void setNfGroupId(std::string const &value);

  friend void to_json(nlohmann::json &j, const NfGroupCond &o);
  friend void from_json(const nlohmann::json &j, NfGroupCond &o);

protected:
  std::string m_NfType;

  std::string m_NfGroupId;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* NfGroupCond_H_ */
