/**
 * 3gpp-nidd
 * API for non IP data delivery. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NiddStatus.h
 *
 * Possible values are - ACTIVE: The NIDD configuration is active. -
 * TERMINATED_UE_NOT_AUTHORIZED: The NIDD configuration was terminated because
 * the UE´s authorisation was revoked. - TERMINATED: The NIDD configuration was
 * terminated. - RDS_PORT_UNKNOWN: The RDS port is unknown.
 */

#ifndef NiddStatus_H_
#define NiddStatus_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Possible values are - ACTIVE: The NIDD configuration is active. -
/// TERMINATED_UE_NOT_AUTHORIZED: The NIDD configuration was terminated because
/// the UE´s authorisation was revoked. - TERMINATED: The NIDD configuration was
/// terminated. - RDS_PORT_UNKNOWN: The RDS port is unknown.
/// </summary>
class NiddStatus {
public:
  NiddStatus();
  virtual ~NiddStatus();

  void validate();

  /////////////////////////////////////////////
  /// NiddStatus members

  friend void to_json(nlohmann::json &j, const NiddStatus &o);
  friend void from_json(const nlohmann::json &j, NiddStatus &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* NiddStatus_H_ */
