/**
 * Nudsf_DataRepository
 * Nudsf Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NotificationDescription.h
 *
 * Description of a record notification
 */

#ifndef NotificationDescription_H_
#define NotificationDescription_H_

#include "RecordOperation.h"
#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Description of a record notification
/// </summary>
class NotificationDescription {
public:
  NotificationDescription();
  virtual ~NotificationDescription();

  void validate();

  /////////////////////////////////////////////
  /// NotificationDescription members

  /// <summary>
  /// String providing an URI formatted according to RFC 3986
  /// </summary>
  std::string getRecordRef() const;
  void setRecordRef(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  RecordOperation getOperationType() const;
  void setOperationType(RecordOperation const &value);
  /// <summary>
  ///
  /// </summary>
  std::string getSubscriptionId() const;
  void setSubscriptionId(std::string const &value);
  bool subscriptionIdIsSet() const;
  void unsetSubscriptionId();

  friend void to_json(nlohmann::json &j, const NotificationDescription &o);
  friend void from_json(const nlohmann::json &j, NotificationDescription &o);

protected:
  std::string m_RecordRef;

  RecordOperation m_OperationType;

  std::string m_SubscriptionId;
  bool m_SubscriptionIdIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* NotificationDescription_H_ */
