/**
 * Nudsf_Timer
 * Nudsf Timer Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PatchOperation.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PatchOperation::PatchOperation() {}

PatchOperation::~PatchOperation() {}

void PatchOperation::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const PatchOperation &o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json &j, PatchOperation &o) {}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
