/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PdnType.h
 *
 * Possible values are - IPV4: PDN connection of IPv4 type. - IPV6: PDN
 * connection of IPv6 type. - IPV4V6: PDN connection of IPv4v6 type. - NON_IP:
 * PDN connection of non-IP type. - ETHERNET: PDN connection of Ethernet type.
 */

#ifndef PdnType_H_
#define PdnType_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Possible values are - IPV4: PDN connection of IPv4 type. - IPV6: PDN
/// connection of IPv6 type. - IPV4V6: PDN connection of IPv4v6 type. - NON_IP:
/// PDN connection of non-IP type. - ETHERNET: PDN connection of Ethernet type.
/// </summary>
class PdnType {
public:
  PdnType();
  virtual ~PdnType();

  void validate();

  /////////////////////////////////////////////
  /// PdnType members

  friend void to_json(nlohmann::json &j, const PdnType &o);
  friend void from_json(const nlohmann::json &j, PdnType &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* PdnType_H_ */
