/**
 * LMF Location
 * LMF Location Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PointAltitudeUncertainty_allOf.h
 *
 *
 */

#ifndef PointAltitudeUncertainty_allOf_H_
#define PointAltitudeUncertainty_allOf_H_

#include "GeographicalCoordinates.h"
#include "UncertaintyEllipse.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class PointAltitudeUncertainty_allOf {
public:
  PointAltitudeUncertainty_allOf();
  virtual ~PointAltitudeUncertainty_allOf();

  void validate();

  /////////////////////////////////////////////
  /// PointAltitudeUncertainty_allOf members

  /// <summary>
  ///
  /// </summary>
  GeographicalCoordinates getPoint() const;
  void setPoint(GeographicalCoordinates const &value);
  /// <summary>
  /// Indicates value of altitude.
  /// </summary>
  double getAltitude() const;
  void setAltitude(double const value);
  /// <summary>
  ///
  /// </summary>
  UncertaintyEllipse getUncertaintyEllipse() const;
  void setUncertaintyEllipse(UncertaintyEllipse const &value);
  /// <summary>
  /// Indicates value of uncertainty.
  /// </summary>
  float getUncertaintyAltitude() const;
  void setUncertaintyAltitude(float const value);
  /// <summary>
  /// Indicates value of confidence.
  /// </summary>
  int32_t getConfidence() const;
  void setConfidence(int32_t const value);

  friend void to_json(nlohmann::json &j,
                      const PointAltitudeUncertainty_allOf &o);
  friend void from_json(const nlohmann::json &j,
                        PointAltitudeUncertainty_allOf &o);

protected:
  GeographicalCoordinates m_Point;

  double m_Altitude;

  UncertaintyEllipse m_UncertaintyEllipse;

  float m_UncertaintyAltitude;

  int32_t m_Confidence;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* PointAltitudeUncertainty_allOf_H_ */
