/**
 * Unified Data Repository Service API file for subscription data
 * Unified Data Repository Service (subscription data). The API version is
 * defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: -
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PpDataType.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PpDataType::PpDataType() {}

PpDataType::~PpDataType() {}

void PpDataType::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const PpDataType &o) { j = nlohmann::json(); }

void from_json(const nlohmann::json &j, PpDataType &o) {}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
