/**
 * Unified Data Repository Service API file for subscription data
 * Unified Data Repository Service (subscription data). The API version is
 * defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: -
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PtwParameters.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PtwParameters::PtwParameters() { m_PtwValue = ""; }

PtwParameters::~PtwParameters() {}

void PtwParameters::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const PtwParameters &o) {
  j = nlohmann::json();
  j["operationMode"] = o.m_OperationMode;
  j["ptwValue"] = o.m_PtwValue;
}

void from_json(const nlohmann::json &j, PtwParameters &o) {
  j.at("operationMode").get_to(o.m_OperationMode);
  j.at("ptwValue").get_to(o.m_PtwValue);
}

OperationMode PtwParameters::getOperationMode() const {
  return m_OperationMode;
}
void PtwParameters::setOperationMode(OperationMode const &value) {
  m_OperationMode = value;
}
std::string PtwParameters::getPtwValue() const { return m_PtwValue; }
void PtwParameters::setPtwValue(std::string const &value) {
  m_PtwValue = value;
}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
