/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "QosFlowNotifyItem.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

QosFlowNotifyItem::QosFlowNotifyItem() {
  m_Qfi = 0;
  m_CurrentQosProfileIndex = 0;
  m_CurrentQosProfileIndexIsSet = false;
  m_NullQoSProfileIndex = false;
  m_NullQoSProfileIndexIsSet = false;
}

QosFlowNotifyItem::~QosFlowNotifyItem() {}

void QosFlowNotifyItem::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const QosFlowNotifyItem &o) {
  j = nlohmann::json();
  j["qfi"] = o.m_Qfi;
  j["notificationCause"] = o.m_NotificationCause;
  if (o.currentQosProfileIndexIsSet())
    j["currentQosProfileIndex"] = o.m_CurrentQosProfileIndex;
  if (o.nullQoSProfileIndexIsSet())
    j["nullQoSProfileIndex"] = o.m_NullQoSProfileIndex;
}

void from_json(const nlohmann::json &j, QosFlowNotifyItem &o) {
  j.at("qfi").get_to(o.m_Qfi);
  j.at("notificationCause").get_to(o.m_NotificationCause);
  if (j.find("currentQosProfileIndex") != j.end()) {
    j.at("currentQosProfileIndex").get_to(o.m_CurrentQosProfileIndex);
    o.m_CurrentQosProfileIndexIsSet = true;
  }
  if (j.find("nullQoSProfileIndex") != j.end()) {
    j.at("nullQoSProfileIndex").get_to(o.m_NullQoSProfileIndex);
    o.m_NullQoSProfileIndexIsSet = true;
  }
}

int32_t QosFlowNotifyItem::getQfi() const { return m_Qfi; }
void QosFlowNotifyItem::setQfi(int32_t const value) { m_Qfi = value; }
NotificationCause QosFlowNotifyItem::getNotificationCause() const {
  return m_NotificationCause;
}
void QosFlowNotifyItem::setNotificationCause(NotificationCause const &value) {
  m_NotificationCause = value;
}
int32_t QosFlowNotifyItem::getCurrentQosProfileIndex() const {
  return m_CurrentQosProfileIndex;
}
void QosFlowNotifyItem::setCurrentQosProfileIndex(int32_t const value) {
  m_CurrentQosProfileIndex = value;
  m_CurrentQosProfileIndexIsSet = true;
}
bool QosFlowNotifyItem::currentQosProfileIndexIsSet() const {
  return m_CurrentQosProfileIndexIsSet;
}
void QosFlowNotifyItem::unsetCurrentQosProfileIndex() {
  m_CurrentQosProfileIndexIsSet = false;
}
bool QosFlowNotifyItem::isNullQoSProfileIndex() const {
  return m_NullQoSProfileIndex;
}
void QosFlowNotifyItem::setNullQoSProfileIndex(bool const value) {
  m_NullQoSProfileIndex = value;
  m_NullQoSProfileIndexIsSet = true;
}
bool QosFlowNotifyItem::nullQoSProfileIndexIsSet() const {
  return m_NullQoSProfileIndexIsSet;
}
void QosFlowNotifyItem::unsetNullQoSProfileIndex() {
  m_NullQoSProfileIndexIsSet = false;
}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
