/**
 * Nhss_EE
 * HSS Event Exposure © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ReachabilityForSmsReport.h
 *
 * Contains data for a Monitoring Event Report, specific to the
 * &#39;Reachability For SMS&#39; event type
 */

#ifndef ReachabilityForSmsReport_H_
#define ReachabilityForSmsReport_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Contains data for a Monitoring Event Report, specific to the
/// &#39;Reachability For SMS&#39; event type
/// </summary>
class ReachabilityForSmsReport {
public:
  ReachabilityForSmsReport();
  virtual ~ReachabilityForSmsReport();

  void validate();

  /////////////////////////////////////////////
  /// ReachabilityForSmsReport members

  /// <summary>
  ///
  /// </summary>
  bool isReachabilitySmsStatus() const;
  void setReachabilitySmsStatus(bool const value);
  /// <summary>
  /// string with format \&quot;date-time\&quot; as defined in OpenAPI.
  /// </summary>
  std::string getMaxAvailabilityTime() const;
  void setMaxAvailabilityTime(std::string const &value);
  bool maxAvailabilityTimeIsSet() const;
  void unsetMaxAvailabilityTime();

  friend void to_json(nlohmann::json &j, const ReachabilityForSmsReport &o);
  friend void from_json(const nlohmann::json &j, ReachabilityForSmsReport &o);

protected:
  bool m_ReachabilitySmsStatus;

  std::string m_MaxAvailabilityTime;
  bool m_MaxAvailabilityTimeIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* ReachabilityForSmsReport_H_ */
