/**
 * Nucmf_UECapabilityManagement
 * Nucmf_UECapabilityManagement Service. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * RedirectResponse.h
 *
 *
 */

#ifndef RedirectResponse_H_
#define RedirectResponse_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class RedirectResponse {
public:
  RedirectResponse();
  virtual ~RedirectResponse();

  void validate();

  /////////////////////////////////////////////
  /// RedirectResponse members

  /// <summary>
  ///
  /// </summary>
  std::string getCause() const;
  void setCause(std::string const &value);
  bool causeIsSet() const;
  void unsetCause();
  /// <summary>
  /// String providing an URI formatted according to RFC 3986
  /// </summary>
  std::string getTargetScp() const;
  void setTargetScp(std::string const &value);
  bool targetScpIsSet() const;
  void unsetTargetScp();

  friend void to_json(nlohmann::json &j, const RedirectResponse &o);
  friend void from_json(const nlohmann::json &j, RedirectResponse &o);

protected:
  std::string m_Cause;
  bool m_CauseIsSet;
  std::string m_TargetScp;
  bool m_TargetScpIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* RedirectResponse_H_ */
