/**
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 3.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "RedirectServer.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

RedirectServer::RedirectServer() { m_RedirectServerAddress = ""; }

RedirectServer::~RedirectServer() {}

void RedirectServer::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const RedirectServer &o) {
  j = nlohmann::json();
  j["redirectAddressType"] = o.m_RedirectAddressType;
  j["redirectServerAddress"] = o.m_RedirectServerAddress;
}

void from_json(const nlohmann::json &j, RedirectServer &o) {
  j.at("redirectAddressType").get_to(o.m_RedirectAddressType);
  j.at("redirectServerAddress").get_to(o.m_RedirectServerAddress);
}

RedirectAddressType RedirectServer::getRedirectAddressType() const {
  return m_RedirectAddressType;
}
void RedirectServer::setRedirectAddressType(RedirectAddressType const &value) {
  m_RedirectAddressType = value;
}
std::string RedirectServer::getRedirectServerAddress() const {
  return m_RedirectServerAddress;
}
void RedirectServer::setRedirectServerAddress(std::string const &value) {
  m_RedirectServerAddress = value;
}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
