/**
 * CAPIF_API_Provider_Management_API
 * API for API provider domain functions management. © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * RegistrationInformation.h
 *
 * Represents registration information of an individual API provider domain
 * function.
 */

#ifndef RegistrationInformation_H_
#define RegistrationInformation_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Represents registration information of an individual API provider domain
/// function.
/// </summary>
class RegistrationInformation {
public:
  RegistrationInformation();
  virtual ~RegistrationInformation();

  void validate();

  /////////////////////////////////////////////
  /// RegistrationInformation members

  /// <summary>
  /// Public Key of API Provider domain function.
  /// </summary>
  std::string getApiProvPubKey() const;
  void setApiProvPubKey(std::string const &value);
  /// <summary>
  /// API provider domain function&#39;s client certificate
  /// </summary>
  std::string getApiProvCert() const;
  void setApiProvCert(std::string const &value);
  bool apiProvCertIsSet() const;
  void unsetApiProvCert();

  friend void to_json(nlohmann::json &j, const RegistrationInformation &o);
  friend void from_json(const nlohmann::json &j, RegistrationInformation &o);

protected:
  std::string m_ApiProvPubKey;

  std::string m_ApiProvCert;
  bool m_ApiProvCertIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* RegistrationInformation_H_ */
