/**
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 3.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * RegistrationChargingInformation.h
 *
 *
 */

#ifndef RegistrationChargingInformation_H_
#define RegistrationChargingInformation_H_

#include "GlobalRanNodeId.h"
#include "MICOModeIndication.h"
#include "NSSAIMap.h"
#include "PSCellInformation.h"
#include "RatType.h"
#include "RegistrationMessageType.h"
#include "ServiceAreaRestriction.h"
#include "SmsIndication.h"
#include "Snssai.h"
#include "Tai.h"
#include "UserInformation.h"
#include "UserLocation.h"
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class RegistrationChargingInformation {
public:
  RegistrationChargingInformation();
  virtual ~RegistrationChargingInformation();

  void validate();

  /////////////////////////////////////////////
  /// RegistrationChargingInformation members

  /// <summary>
  ///
  /// </summary>
  RegistrationMessageType getRegistrationMessagetype() const;
  void setRegistrationMessagetype(RegistrationMessageType const &value);
  /// <summary>
  ///
  /// </summary>
  UserInformation getUserInformation() const;
  void setUserInformation(UserInformation const &value);
  bool userInformationIsSet() const;
  void unsetUserInformation();
  /// <summary>
  ///
  /// </summary>
  UserLocation getUserLocationinfo() const;
  void setUserLocationinfo(UserLocation const &value);
  bool userLocationinfoIsSet() const;
  void unsetUserLocationinfo();
  /// <summary>
  ///
  /// </summary>
  PSCellInformation getPSCellInformation() const;
  void setPSCellInformation(PSCellInformation const &value);
  bool pSCellInformationIsSet() const;
  void unsetPSCellInformation();
  /// <summary>
  /// String with format \&quot;&lt;time-numoffset&gt;\&quot; optionally
  /// appended by \&quot;&lt;daylightSavingTime&gt;\&quot;, where -
  /// &lt;time-numoffset&gt; shall represent the time zone adjusted for daylight
  /// saving time and be encoded as time-numoffset as defined in clause 5.6 of
  /// IETF RFC 3339; - &lt;daylightSavingTime&gt; shall represent the adjustment
  /// that has been made and shall be encoded as \&quot;+1\&quot; or
  /// \&quot;+2\&quot; for a +1 or +2 hours adjustment. The example is for 8
  /// hours behind UTC, +1 hour adjustment for Daylight Saving Time.
  /// </summary>
  std::string getUetimeZone() const;
  void setUetimeZone(std::string const &value);
  bool uetimeZoneIsSet() const;
  void unsetUetimeZone();
  /// <summary>
  ///
  /// </summary>
  RatType getRATType() const;
  void setRATType(RatType const &value);
  bool rATTypeIsSet() const;
  void unsetRATType();
  /// <summary>
  /// string with format \&quot;bytes\&quot; as defined in OpenAPI
  /// </summary>
  std::string getR5GMMCapability() const;
  void setR5GMMCapability(std::string const &value);
  bool r5GMMCapabilityIsSet() const;
  void unsetr_5GMMCapability();
  /// <summary>
  ///
  /// </summary>
  MICOModeIndication getMICOModeIndication() const;
  void setMICOModeIndication(MICOModeIndication const &value);
  bool mICOModeIndicationIsSet() const;
  void unsetMICOModeIndication();
  /// <summary>
  ///
  /// </summary>
  SmsIndication getSmsIndication() const;
  void setSmsIndication(SmsIndication const &value);
  bool smsIndicationIsSet() const;
  void unsetSmsIndication();
  /// <summary>
  ///
  /// </summary>
  std::vector<Tai> &getTaiList();
  void setTaiList(std::vector<Tai> const &value);
  bool taiListIsSet() const;
  void unsetTaiList();
  /// <summary>
  ///
  /// </summary>
  std::vector<ServiceAreaRestriction> &getServiceAreaRestriction();
  void
  setServiceAreaRestriction(std::vector<ServiceAreaRestriction> const &value);
  bool serviceAreaRestrictionIsSet() const;
  void unsetServiceAreaRestriction();
  /// <summary>
  ///
  /// </summary>
  std::vector<Snssai> &getRequestedNSSAI();
  void setRequestedNSSAI(std::vector<Snssai> const &value);
  bool requestedNSSAIIsSet() const;
  void unsetRequestedNSSAI();
  /// <summary>
  ///
  /// </summary>
  std::vector<Snssai> &getAllowedNSSAI();
  void setAllowedNSSAI(std::vector<Snssai> const &value);
  bool allowedNSSAIIsSet() const;
  void unsetAllowedNSSAI();
  /// <summary>
  ///
  /// </summary>
  std::vector<Snssai> &getRejectedNSSAI();
  void setRejectedNSSAI(std::vector<Snssai> const &value);
  bool rejectedNSSAIIsSet() const;
  void unsetRejectedNSSAI();
  /// <summary>
  ///
  /// </summary>
  std::vector<NSSAIMap> &getNSSAIMapList();
  void setNSSAIMapList(std::vector<NSSAIMap> const &value);
  bool nSSAIMapListIsSet() const;
  void unsetNSSAIMapList();
  /// <summary>
  ///
  /// </summary>
  int32_t getAmfUeNgapId() const;
  void setAmfUeNgapId(int32_t const value);
  bool amfUeNgapIdIsSet() const;
  void unsetAmfUeNgapId();
  /// <summary>
  ///
  /// </summary>
  int32_t getRanUeNgapId() const;
  void setRanUeNgapId(int32_t const value);
  bool ranUeNgapIdIsSet() const;
  void unsetRanUeNgapId();
  /// <summary>
  ///
  /// </summary>
  GlobalRanNodeId getRanNodeId() const;
  void setRanNodeId(GlobalRanNodeId const &value);
  bool ranNodeIdIsSet() const;
  void unsetRanNodeId();

  friend void to_json(nlohmann::json &j,
                      const RegistrationChargingInformation &o);
  friend void from_json(const nlohmann::json &j,
                        RegistrationChargingInformation &o);

protected:
  RegistrationMessageType m_RegistrationMessagetype;

  UserInformation m_UserInformation;
  bool m_UserInformationIsSet;
  UserLocation m_UserLocationinfo;
  bool m_UserLocationinfoIsSet;
  PSCellInformation m_PSCellInformation;
  bool m_PSCellInformationIsSet;
  std::string m_UetimeZone;
  bool m_UetimeZoneIsSet;
  RatType m_RATType;
  bool m_RATTypeIsSet;
  std::string m_r_5GMMCapability;
  bool m_r_5GMMCapabilityIsSet;
  MICOModeIndication m_MICOModeIndication;
  bool m_MICOModeIndicationIsSet;
  SmsIndication m_SmsIndication;
  bool m_SmsIndicationIsSet;
  std::vector<Tai> m_TaiList;
  bool m_TaiListIsSet;
  std::vector<ServiceAreaRestriction> m_ServiceAreaRestriction;
  bool m_ServiceAreaRestrictionIsSet;
  std::vector<Snssai> m_RequestedNSSAI;
  bool m_RequestedNSSAIIsSet;
  std::vector<Snssai> m_AllowedNSSAI;
  bool m_AllowedNSSAIIsSet;
  std::vector<Snssai> m_RejectedNSSAI;
  bool m_RejectedNSSAIIsSet;
  std::vector<NSSAIMap> m_NSSAIMapList;
  bool m_NSSAIMapListIsSet;
  int32_t m_AmfUeNgapId;
  bool m_AmfUeNgapIdIsSet;
  int32_t m_RanUeNgapId;
  bool m_RanUeNgapIdIsSet;
  GlobalRanNodeId m_RanNodeId;
  bool m_RanNodeIdIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* RegistrationChargingInformation_H_ */
