/**
 * Nnef_SMContext
 * Nnef SMContext Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ReleaseCause.h
 *
 * The cause to release the SM Context. Possible values are -
 * PDU_SESSION_RELEASED: Indicates that the Individual SM Context for NIDD is
 * released.
 */

#ifndef ReleaseCause_H_
#define ReleaseCause_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// The cause to release the SM Context. Possible values are -
/// PDU_SESSION_RELEASED: Indicates that the Individual SM Context for NIDD is
/// released.
/// </summary>
class ReleaseCause {
public:
  ReleaseCause();
  virtual ~ReleaseCause();

  void validate();

  /////////////////////////////////////////////
  /// ReleaseCause members

  friend void to_json(nlohmann::json &j, const ReleaseCause &o);
  friend void from_json(const nlohmann::json &j, ReleaseCause &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* ReleaseCause_H_ */
