/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ReportingFrequency.h
 *
 * Indicates the frequency for the reporting.
 */

#ifndef ReportingFrequency_H_
#define ReportingFrequency_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Indicates the frequency for the reporting.
/// </summary>
class ReportingFrequency {
public:
  ReportingFrequency();
  virtual ~ReportingFrequency();

  void validate();

  /////////////////////////////////////////////
  /// ReportingFrequency members

  friend void to_json(nlohmann::json &j, const ReportingFrequency &o);
  friend void from_json(const nlohmann::json &j, ReportingFrequency &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* ReportingFrequency_H_ */
