/**
 * Nhss_EE
 * HSS Event Exposure © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Report.h
 *
 * Contains data for a given Monitoring Event Report
 */

#ifndef Report_H_
#define Report_H_

#include "ReachabilityForSmsReport.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Contains data for a given Monitoring Event Report
/// </summary>
class Report {
public:
  Report();
  virtual ~Report();

  void validate();

  /////////////////////////////////////////////
  /// Report members

  /// <summary>
  ///
  /// </summary>
  ReachabilityForSmsReport getReachabilityForSmsReport() const;
  void setReachabilityForSmsReport(ReachabilityForSmsReport const &value);
  bool reachabilityForSmsReportIsSet() const;
  void unsetReachabilityForSmsReport();

  friend void to_json(nlohmann::json &j, const Report &o);
  friend void from_json(const nlohmann::json &j, Report &o);

protected:
  ReachabilityForSmsReport m_ReachabilityForSmsReport;
  bool m_ReachabilityForSmsReportIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* Report_H_ */
