/**
 * Nhss_imsSDM
 * Nhss Subscriber Data Management Service for IMS. © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SdpDescription.h
 *
 *
 */

#ifndef SdpDescription_H_
#define SdpDescription_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class SdpDescription {
public:
  SdpDescription();
  virtual ~SdpDescription();

  void validate();

  /////////////////////////////////////////////
  /// SdpDescription members

  /// <summary>
  ///
  /// </summary>
  std::string getLine() const;
  void setLine(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  std::string getContent() const;
  void setContent(std::string const &value);
  bool contentIsSet() const;
  void unsetContent();

  friend void to_json(nlohmann::json &j, const SdpDescription &o);
  friend void from_json(const nlohmann::json &j, SdpDescription &o);

protected:
  std::string m_Line;

  std::string m_Content;
  bool m_ContentIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* SdpDescription_H_ */
