/**
 * SS_Events
 * API for SEAL Events management. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SEALEventSubscription.h
 *
 * Represents an individual SEAL Event Subscription resource.
 */

#ifndef SEALEventSubscription_H_
#define SEALEventSubscription_H_

#include "EventSubscription.h"
#include "ReportingInformation.h"
#include "SEALEventDetail.h"
#include "WebsockNotifConfig.h"
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Represents an individual SEAL Event Subscription resource.
/// </summary>
class SEALEventSubscription {
public:
  SEALEventSubscription();
  virtual ~SEALEventSubscription();

  void validate();

  /////////////////////////////////////////////
  /// SEALEventSubscription members

  /// <summary>
  /// String identifying the subscriber of the event.
  /// </summary>
  std::string getSubscriberId() const;
  void setSubscriberId(std::string const &value);
  /// <summary>
  /// Subscribed events.
  /// </summary>
  std::vector<EventSubscription> &getEventSubs();
  void setEventSubs(std::vector<EventSubscription> const &value);
  /// <summary>
  ///
  /// </summary>
  ReportingInformation getEventReq() const;
  void setEventReq(ReportingInformation const &value);
  /// <summary>
  /// string providing an URI formatted according to IETF RFC 3986.
  /// </summary>
  std::string getNotificationDestination() const;
  void setNotificationDestination(std::string const &value);
  /// <summary>
  /// Set to true by Subscriber to request the SEAL server to send a test
  /// notification. Set to false or omitted otherwise.
  /// </summary>
  bool isRequestTestNotification() const;
  void setRequestTestNotification(bool const value);
  bool requestTestNotificationIsSet() const;
  void unsetRequestTestNotification();
  /// <summary>
  ///
  /// </summary>
  WebsockNotifConfig getWebsockNotifConfig() const;
  void setWebsockNotifConfig(WebsockNotifConfig const &value);
  bool websockNotifConfigIsSet() const;
  void unsetWebsockNotifConfig();
  /// <summary>
  ///
  /// </summary>
  std::vector<SEALEventDetail> &getEventDetails();
  void setEventDetails(std::vector<SEALEventDetail> const &value);
  bool eventDetailsIsSet() const;
  void unsetEventDetails();
  /// <summary>
  /// A string used to indicate the features supported by an API that is used as
  /// defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a
  /// bitmask indicating supported features in hexadecimal representation Each
  /// character in the string shall take a value of \&quot;0\&quot; to
  /// \&quot;9\&quot;, \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to
  /// \&quot;F\&quot; and shall represent the support of 4 features as described
  /// in table 5.2.2-3. The most significant character representing the
  /// highest-numbered features shall appear first in the string, and the
  /// character representing features 1 to 4 shall appear last in the string.
  /// The list of features and their numbering (starting with 1) are defined
  /// separately for each API. If the string contains a lower number of
  /// characters than there are defined features for an API, all features that
  /// would be represented by characters that are not present in the string are
  /// not supported
  /// </summary>
  std::string getSuppFeat() const;
  void setSuppFeat(std::string const &value);
  bool suppFeatIsSet() const;
  void unsetSuppFeat();

  friend void to_json(nlohmann::json &j, const SEALEventSubscription &o);
  friend void from_json(const nlohmann::json &j, SEALEventSubscription &o);

protected:
  std::string m_SubscriberId;

  std::vector<EventSubscription> m_EventSubs;

  ReportingInformation m_EventReq;

  std::string m_NotificationDestination;

  bool m_RequestTestNotification;
  bool m_RequestTestNotificationIsSet;
  WebsockNotifConfig m_WebsockNotifConfig;
  bool m_WebsockNotifConfigIsSet;
  std::vector<SEALEventDetail> m_EventDetails;
  bool m_EventDetailsIsSet;
  std::string m_SuppFeat;
  bool m_SuppFeatIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* SEALEventSubscription_H_ */
