/**
 * NRF NFManagement Service
 * NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SeppInfo.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SeppInfo::SeppInfo() {
  m_SeppPortsIsSet = false;
  m_RemotePlmnListIsSet = false;
}

SeppInfo::~SeppInfo() {}

void SeppInfo::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const SeppInfo &o) {
  j = nlohmann::json();
  if (o.seppPortsIsSet() || !o.m_SeppPorts.empty())
    j["seppPorts"] = o.m_SeppPorts;
  if (o.remotePlmnListIsSet() || !o.m_RemotePlmnList.empty())
    j["remotePlmnList"] = o.m_RemotePlmnList;
}

void from_json(const nlohmann::json &j, SeppInfo &o) {
  if (j.find("seppPorts") != j.end()) {
    j.at("seppPorts").get_to(o.m_SeppPorts);
    o.m_SeppPortsIsSet = true;
  }
  if (j.find("remotePlmnList") != j.end()) {
    j.at("remotePlmnList").get_to(o.m_RemotePlmnList);
    o.m_RemotePlmnListIsSet = true;
  }
}

std::map<std::string, int32_t> &SeppInfo::getSeppPorts() { return m_SeppPorts; }
void SeppInfo::setSeppPorts(std::map<std::string, int32_t> const value) {
  m_SeppPorts = value;
  m_SeppPortsIsSet = true;
}
bool SeppInfo::seppPortsIsSet() const { return m_SeppPortsIsSet; }
void SeppInfo::unsetSeppPorts() { m_SeppPortsIsSet = false; }
std::vector<PlmnId> &SeppInfo::getRemotePlmnList() { return m_RemotePlmnList; }
void SeppInfo::setRemotePlmnList(std::vector<PlmnId> const &value) {
  m_RemotePlmnList = value;
  m_RemotePlmnListIsSet = true;
}
bool SeppInfo::remotePlmnListIsSet() const { return m_RemotePlmnListIsSet; }
void SeppInfo::unsetRemotePlmnList() { m_RemotePlmnListIsSet = false; }

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
