/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ServAuthInfo.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

ServAuthInfo::ServAuthInfo() {}

ServAuthInfo::~ServAuthInfo() {}

void ServAuthInfo::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const ServAuthInfo &o) { j = nlohmann::json(); }

void from_json(const nlohmann::json &j, ServAuthInfo &o) {}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
