/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SgsnAddress.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SgsnAddress::SgsnAddress() {
  m_SgsnIpv4Addr = "";
  m_SgsnIpv4AddrIsSet = false;
  m_SgsnIpv6AddrIsSet = false;
}

SgsnAddress::~SgsnAddress() {}

void SgsnAddress::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const SgsnAddress &o) {
  j = nlohmann::json();
  if (o.sgsnIpv4AddrIsSet())
    j["sgsnIpv4Addr"] = o.m_SgsnIpv4Addr;
  if (o.sgsnIpv6AddrIsSet())
    j["sgsnIpv6Addr"] = o.m_SgsnIpv6Addr;
}

void from_json(const nlohmann::json &j, SgsnAddress &o) {
  if (j.find("sgsnIpv4Addr") != j.end()) {
    j.at("sgsnIpv4Addr").get_to(o.m_SgsnIpv4Addr);
    o.m_SgsnIpv4AddrIsSet = true;
  }
  if (j.find("sgsnIpv6Addr") != j.end()) {
    j.at("sgsnIpv6Addr").get_to(o.m_SgsnIpv6Addr);
    o.m_SgsnIpv6AddrIsSet = true;
  }
}

std::string SgsnAddress::getSgsnIpv4Addr() const { return m_SgsnIpv4Addr; }
void SgsnAddress::setSgsnIpv4Addr(std::string const &value) {
  m_SgsnIpv4Addr = value;
  m_SgsnIpv4AddrIsSet = true;
}
bool SgsnAddress::sgsnIpv4AddrIsSet() const { return m_SgsnIpv4AddrIsSet; }
void SgsnAddress::unsetSgsnIpv4Addr() { m_SgsnIpv4AddrIsSet = false; }
Ipv6Addr SgsnAddress::getSgsnIpv6Addr() const { return m_SgsnIpv6Addr; }
void SgsnAddress::setSgsnIpv6Addr(Ipv6Addr const &value) {
  m_SgsnIpv6Addr = value;
  m_SgsnIpv6AddrIsSet = true;
}
bool SgsnAddress::sgsnIpv6AddrIsSet() const { return m_SgsnIpv6AddrIsSet; }
void SgsnAddress::unsetSgsnIpv6Addr() { m_SgsnIpv6AddrIsSet = false; }

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
