/**
 * Nsoraf_SOR
 * Nsoraf Steering Of Roaming Service. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SorAckInfo.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SorAckInfo::SorAckInfo() { m_SorSendingTime = ""; }

SorAckInfo::~SorAckInfo() {}

void SorAckInfo::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const SorAckInfo &o) {
  j = nlohmann::json();
  j["sorAckStatus"] = o.m_SorAckStatus;
  j["sorSendingTime"] = o.m_SorSendingTime;
}

void from_json(const nlohmann::json &j, SorAckInfo &o) {
  j.at("sorAckStatus").get_to(o.m_SorAckStatus);
  j.at("sorSendingTime").get_to(o.m_SorSendingTime);
}

SorAckStatus SorAckInfo::getSorAckStatus() const { return m_SorAckStatus; }
void SorAckInfo::setSorAckStatus(SorAckStatus const &value) {
  m_SorAckStatus = value;
}
std::string SorAckInfo::getSorSendingTime() const { return m_SorSendingTime; }
void SorAckInfo::setSorSendingTime(std::string const &value) {
  m_SorSendingTime = value;
}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
