/**
 * Unified Data Repository Service API file for policy data
 * The API version is defined in 3GPP TS 29.504 © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: -
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SponsorConnectivityData.h
 *
 * Contains the sponsored data connectivity related information for a sponsor
 * identifier.
 */

#ifndef SponsorConnectivityData_H_
#define SponsorConnectivityData_H_

#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Contains the sponsored data connectivity related information for a sponsor
/// identifier.
/// </summary>
class SponsorConnectivityData {
public:
  SponsorConnectivityData();
  virtual ~SponsorConnectivityData();

  void validate();

  /////////////////////////////////////////////
  /// SponsorConnectivityData members

  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> &getAspIds();
  void setAspIds(std::vector<std::string> const &value);

  friend void to_json(nlohmann::json &j, const SponsorConnectivityData &o);
  friend void from_json(const nlohmann::json &j, SponsorConnectivityData &o);

protected:
  std::vector<std::string> m_AspIds;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* SponsorConnectivityData_H_ */
