/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "StatusInfo.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

StatusInfo::StatusInfo() {
  m_CauseIsSet = false;
  m_CnAssistedRanParaIsSet = false;
  m_AnTypeIsSet = false;
}

StatusInfo::~StatusInfo() {}

void StatusInfo::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const StatusInfo &o) {
  j = nlohmann::json();
  j["resourceStatus"] = o.m_ResourceStatus;
  if (o.causeIsSet())
    j["cause"] = o.m_Cause;
  if (o.cnAssistedRanParaIsSet())
    j["cnAssistedRanPara"] = o.m_CnAssistedRanPara;
  if (o.anTypeIsSet())
    j["anType"] = o.m_AnType;
}

void from_json(const nlohmann::json &j, StatusInfo &o) {
  j.at("resourceStatus").get_to(o.m_ResourceStatus);
  if (j.find("cause") != j.end()) {
    j.at("cause").get_to(o.m_Cause);
    o.m_CauseIsSet = true;
  }
  if (j.find("cnAssistedRanPara") != j.end()) {
    j.at("cnAssistedRanPara").get_to(o.m_CnAssistedRanPara);
    o.m_CnAssistedRanParaIsSet = true;
  }
  if (j.find("anType") != j.end()) {
    j.at("anType").get_to(o.m_AnType);
    o.m_AnTypeIsSet = true;
  }
}

ResourceStatus StatusInfo::getResourceStatus() const {
  return m_ResourceStatus;
}
void StatusInfo::setResourceStatus(ResourceStatus const &value) {
  m_ResourceStatus = value;
}
Cause StatusInfo::getCause() const { return m_Cause; }
void StatusInfo::setCause(Cause const &value) {
  m_Cause = value;
  m_CauseIsSet = true;
}
bool StatusInfo::causeIsSet() const { return m_CauseIsSet; }
void StatusInfo::unsetCause() { m_CauseIsSet = false; }
CnAssistedRanPara StatusInfo::getCnAssistedRanPara() const {
  return m_CnAssistedRanPara;
}
void StatusInfo::setCnAssistedRanPara(CnAssistedRanPara const &value) {
  m_CnAssistedRanPara = value;
  m_CnAssistedRanParaIsSet = true;
}
bool StatusInfo::cnAssistedRanParaIsSet() const {
  return m_CnAssistedRanParaIsSet;
}
void StatusInfo::unsetCnAssistedRanPara() { m_CnAssistedRanParaIsSet = false; }
AccessType StatusInfo::getAnType() const { return m_AnType; }
void StatusInfo::setAnType(AccessType const &value) {
  m_AnType = value;
  m_AnTypeIsSet = true;
}
bool StatusInfo::anTypeIsSet() const { return m_AnTypeIsSet; }
void StatusInfo::unsetAnType() { m_AnTypeIsSet = false; }

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
