/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SteerModeIndicator.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SteerModeIndicator::SteerModeIndicator() {}

SteerModeIndicator::~SteerModeIndicator() {}

void SteerModeIndicator::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const SteerModeIndicator &o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json &j, SteerModeIndicator &o) {}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
