/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SubscribedDefaultQos.h
 *
 * Provides the subsribed 5QI and the ARP, it may contain the priority level.
 */

#ifndef SubscribedDefaultQos_H_
#define SubscribedDefaultQos_H_

#include "Arp.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Provides the subsribed 5QI and the ARP, it may contain the priority level.
/// </summary>
class SubscribedDefaultQos {
public:
  SubscribedDefaultQos();
  virtual ~SubscribedDefaultQos();

  void validate();

  /////////////////////////////////////////////
  /// SubscribedDefaultQos members

  /// <summary>
  /// Unsigned integer representing a 5G QoS Identifier (see clause 5.7.2.1 of
  /// 3GPP TS 23.501, within the range 0 to 255
  /// </summary>
  int32_t getR5qi() const;
  void setR5qi(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  Arp getArp() const;
  void setArp(Arp const &value);
  /// <summary>
  /// Unsigned integer indicating the 5QI Priority Level (see clauses 5.7.3.3
  /// and 5.7.4 of 3GPP TS 23.501, within the range 1 to 127.Values are ordered
  /// in decreasing order of priority, i.e. with 1 as the highest priority and
  /// 127 as the lowest priority.
  /// </summary>
  int32_t getPriorityLevel() const;
  void setPriorityLevel(int32_t const value);
  bool priorityLevelIsSet() const;
  void unsetPriorityLevel();

  friend void to_json(nlohmann::json &j, const SubscribedDefaultQos &o);
  friend void from_json(const nlohmann::json &j, SubscribedDefaultQos &o);

protected:
  int32_t m_r_5qi;

  Arp m_Arp;

  int32_t m_PriorityLevel;
  bool m_PriorityLevelIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* SubscribedDefaultQos_H_ */
