/**
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 3.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SvcExperience.h
 *
 * Contains a mean opinion score with the customized range.
 */

#ifndef SvcExperience_H_
#define SvcExperience_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Contains a mean opinion score with the customized range.
/// </summary>
class SvcExperience {
public:
  SvcExperience();
  virtual ~SvcExperience();

  void validate();

  /////////////////////////////////////////////
  /// SvcExperience members

  /// <summary>
  /// string with format \&quot;float\&quot; as defined in OpenAPI.
  /// </summary>
  float getMos() const;
  void setMos(float const value);
  bool mosIsSet() const;
  void unsetMos();
  /// <summary>
  /// string with format \&quot;float\&quot; as defined in OpenAPI.
  /// </summary>
  float getUpperRange() const;
  void setUpperRange(float const value);
  bool upperRangeIsSet() const;
  void unsetUpperRange();
  /// <summary>
  /// string with format \&quot;float\&quot; as defined in OpenAPI.
  /// </summary>
  float getLowerRange() const;
  void setLowerRange(float const value);
  bool lowerRangeIsSet() const;
  void unsetLowerRange();

  friend void to_json(nlohmann::json &j, const SvcExperience &o);
  friend void from_json(const nlohmann::json &j, SvcExperience &o);

protected:
  float m_Mos;
  bool m_MosIsSet;
  float m_UpperRange;
  bool m_UpperRangeIsSet;
  float m_LowerRange;
  bool m_LowerRangeIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* SvcExperience_H_ */
