/**
 * Nhss_imsSDM
 * Nhss Subscriber Data Management Service for IMS. © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TadsInformation.h
 *
 *
 */

#ifndef TadsInformation_H_
#define TadsInformation_H_

#include "AccessType_2.h"
#include "ImsVoiceOverPsSessionSupport.h"
#include "RatType.h"
#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class TadsInformation {
public:
  TadsInformation();
  virtual ~TadsInformation();

  void validate();

  /////////////////////////////////////////////
  /// TadsInformation members

  /// <summary>
  ///
  /// </summary>
  ImsVoiceOverPsSessionSupport getVoiceOverPsSessionSupport() const;
  void setVoiceOverPsSessionSupport(ImsVoiceOverPsSessionSupport const &value);
  /// <summary>
  ///
  /// </summary>
  AccessType_2 getAccessType() const;
  void setAccessType(AccessType_2 const &value);
  bool accessTypeIsSet() const;
  void unsetAccessType();
  /// <summary>
  ///
  /// </summary>
  RatType getRatType() const;
  void setRatType(RatType const &value);
  bool ratTypeIsSet() const;
  void unsetRatType();
  /// <summary>
  /// string with format \&quot;date-time\&quot; as defined in OpenAPI.
  /// </summary>
  std::string getLastUeActivityTime() const;
  void setLastUeActivityTime(std::string const &value);
  bool lastUeActivityTimeIsSet() const;
  void unsetLastUeActivityTime();

  friend void to_json(nlohmann::json &j, const TadsInformation &o);
  friend void from_json(const nlohmann::json &j, TadsInformation &o);

protected:
  ImsVoiceOverPsSessionSupport m_VoiceOverPsSessionSupport;

  AccessType_2 m_AccessType;
  bool m_AccessTypeIsSet;
  RatType m_RatType;
  bool m_RatTypeIsSet;
  std::string m_LastUeActivityTime;
  bool m_LastUeActivityTimeIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* TadsInformation_H_ */
