/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TimeUnit.h
 *
 * Possible values are - MINUTE: Time unit is per minute. - HOUR: Time unit is
 * per hour. - DAY: Time unit is per day.
 */

#ifndef TimeUnit_H_
#define TimeUnit_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Possible values are - MINUTE: Time unit is per minute. - HOUR: Time unit is
/// per hour. - DAY: Time unit is per day.
/// </summary>
class TimeUnit {
public:
  TimeUnit();
  virtual ~TimeUnit();

  void validate();

  /////////////////////////////////////////////
  /// TimeUnit members

  friend void to_json(nlohmann::json &j, const TimeUnit &o);
  friend void from_json(const nlohmann::json &j, TimeUnit &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* TimeUnit_H_ */
