/**
 * GMDviaMBMSbyMB2
 * API for Group Message Delivery via MBMS by MB2 © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TMGIAllocationPatch.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

TMGIAllocationPatch::TMGIAllocationPatch() {
  m_ExternalGroupId = "";
  m_ExternalGroupIdIsSet = false;
  m_MbmsLocAreaIsSet = false;
}

TMGIAllocationPatch::~TMGIAllocationPatch() {}

void TMGIAllocationPatch::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const TMGIAllocationPatch &o) {
  j = nlohmann::json();
  if (o.externalGroupIdIsSet())
    j["externalGroupId"] = o.m_ExternalGroupId;
  if (o.mbmsLocAreaIsSet())
    j["mbmsLocArea"] = o.m_MbmsLocArea;
}

void from_json(const nlohmann::json &j, TMGIAllocationPatch &o) {
  if (j.find("externalGroupId") != j.end()) {
    j.at("externalGroupId").get_to(o.m_ExternalGroupId);
    o.m_ExternalGroupIdIsSet = true;
  }
  if (j.find("mbmsLocArea") != j.end()) {
    j.at("mbmsLocArea").get_to(o.m_MbmsLocArea);
    o.m_MbmsLocAreaIsSet = true;
  }
}

std::string TMGIAllocationPatch::getExternalGroupId() const {
  return m_ExternalGroupId;
}
void TMGIAllocationPatch::setExternalGroupId(std::string const &value) {
  m_ExternalGroupId = value;
  m_ExternalGroupIdIsSet = true;
}
bool TMGIAllocationPatch::externalGroupIdIsSet() const {
  return m_ExternalGroupIdIsSet;
}
void TMGIAllocationPatch::unsetExternalGroupId() {
  m_ExternalGroupIdIsSet = false;
}
MbmsLocArea TMGIAllocationPatch::getMbmsLocArea() const {
  return m_MbmsLocArea;
}
void TMGIAllocationPatch::setMbmsLocArea(MbmsLocArea const &value) {
  m_MbmsLocArea = value;
  m_MbmsLocAreaIsSet = true;
}
bool TMGIAllocationPatch::mbmsLocAreaIsSet() const {
  return m_MbmsLocAreaIsSet;
}
void TMGIAllocationPatch::unsetMbmsLocArea() { m_MbmsLocAreaIsSet = false; }

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
