/**
 * Npcf_BDTPolicyControl Service API
 * PCF BDT Policy Control Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TransferPolicy.h
 *
 * Describes a transfer policy.
 */

#ifndef TransferPolicy_H_
#define TransferPolicy_H_

#include "TimeWindow.h"
#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Describes a transfer policy.
/// </summary>
class TransferPolicy {
public:
  TransferPolicy();
  virtual ~TransferPolicy();

  void validate();

  /////////////////////////////////////////////
  /// TransferPolicy members

  /// <summary>
  /// String representing a bit rate that shall be formatted as follows.
  /// </summary>
  std::string getMaxBitRateDl() const;
  void setMaxBitRateDl(std::string const &value);
  bool maxBitRateDlIsSet() const;
  void unsetMaxBitRateDl();
  /// <summary>
  /// String representing a bit rate that shall be formatted as follows.
  /// </summary>
  std::string getMaxBitRateUl() const;
  void setMaxBitRateUl(std::string const &value);
  bool maxBitRateUlIsSet() const;
  void unsetMaxBitRateUl();
  /// <summary>
  /// Indicates a rating group for the recommended time window.
  /// </summary>
  int32_t getRatingGroup() const;
  void setRatingGroup(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  TimeWindow getRecTimeInt() const;
  void setRecTimeInt(TimeWindow const &value);
  /// <summary>
  /// Contains an identity of a transfer policy.
  /// </summary>
  int32_t getTransPolicyId() const;
  void setTransPolicyId(int32_t const value);

  friend void to_json(nlohmann::json &j, const TransferPolicy &o);
  friend void from_json(const nlohmann::json &j, TransferPolicy &o);

protected:
  std::string m_MaxBitRateDl;
  bool m_MaxBitRateDlIsSet;
  std::string m_MaxBitRateUl;
  bool m_MaxBitRateUlIsSet;
  int32_t m_RatingGroup;

  TimeWindow m_RecTimeInt;

  int32_t m_TransPolicyId;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* TransferPolicy_H_ */
