/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TriggerType.h
 *
 *
 */

#ifndef TriggerType_H_
#define TriggerType_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class TriggerType {
public:
  TriggerType();
  virtual ~TriggerType();

  void validate();

  /////////////////////////////////////////////
  /// TriggerType members

  friend void to_json(nlohmann::json &j, const TriggerType &o);
  friend void from_json(const nlohmann::json &j, TriggerType &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* TriggerType_H_ */
