/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UeContextRelocateData.h
 *
 * Data within a Relocate UE Context request
 */

#ifndef UeContextRelocateData_H_
#define UeContextRelocateData_H_

#include "N2InfoContent.h"
#include "N2SmInformation.h"
#include "NgApCause.h"
#include "NgRanTargetId.h"
#include "RefToBinaryData.h"
#include "UeContext.h"
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Data within a Relocate UE Context request
/// </summary>
class UeContextRelocateData {
public:
  UeContextRelocateData();
  virtual ~UeContextRelocateData();

  void validate();

  /////////////////////////////////////////////
  /// UeContextRelocateData members

  /// <summary>
  ///
  /// </summary>
  UeContext getUeContext() const;
  void setUeContext(UeContext const &value);
  /// <summary>
  ///
  /// </summary>
  NgRanTargetId getTargetId() const;
  void setTargetId(NgRanTargetId const &value);
  /// <summary>
  ///
  /// </summary>
  N2InfoContent getSourceToTargetData() const;
  void setSourceToTargetData(N2InfoContent const &value);
  /// <summary>
  ///
  /// </summary>
  RefToBinaryData getForwardRelocationRequest() const;
  void setForwardRelocationRequest(RefToBinaryData const &value);
  /// <summary>
  ///
  /// </summary>
  std::vector<N2SmInformation> &getPduSessionList();
  void setPduSessionList(std::vector<N2SmInformation> const &value);
  bool pduSessionListIsSet() const;
  void unsetPduSessionList();
  /// <summary>
  ///
  /// </summary>
  N2InfoContent getUeRadioCapability() const;
  void setUeRadioCapability(N2InfoContent const &value);
  bool ueRadioCapabilityIsSet() const;
  void unsetUeRadioCapability();
  /// <summary>
  ///
  /// </summary>
  NgApCause getNgapCause() const;
  void setNgapCause(NgApCause const &value);
  bool ngapCauseIsSet() const;
  void unsetNgapCause();
  /// <summary>
  /// A string used to indicate the features supported by an API that is used as
  /// defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a
  /// bitmask indicating supported features in hexadecimal representation Each
  /// character in the string shall take a value of \&quot;0\&quot; to
  /// \&quot;9\&quot;, \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to
  /// \&quot;F\&quot; and shall represent the support of 4 features as described
  /// in table 5.2.2-3. The most significant character representing the
  /// highest-numbered features shall appear first in the string, and the
  /// character representing features 1 to 4 shall appear last in the string.
  /// The list of features and their numbering (starting with 1) are defined
  /// separately for each API. If the string contains a lower number of
  /// characters than there are defined features for an API, all features that
  /// would be represented by characters that are not present in the string are
  /// not supported
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const &value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();

  friend void to_json(nlohmann::json &j, const UeContextRelocateData &o);
  friend void from_json(const nlohmann::json &j, UeContextRelocateData &o);

protected:
  UeContext m_UeContext;

  NgRanTargetId m_TargetId;

  N2InfoContent m_SourceToTargetData;

  RefToBinaryData m_ForwardRelocationRequest;

  std::vector<N2SmInformation> m_PduSessionList;
  bool m_PduSessionListIsSet;
  N2InfoContent m_UeRadioCapability;
  bool m_UeRadioCapabilityIsSet;
  NgApCause m_NgapCause;
  bool m_NgapCauseIsSet;
  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* UeContextRelocateData_H_ */
