/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UeContextTransferReqData.h
 *
 * Data within a UE Context Transfer Request to start transferring of an
 * individual ueContext resource from old AMF to new AMF
 */

#ifndef UeContextTransferReqData_H_
#define UeContextTransferReqData_H_

#include "AccessType.h"
#include "N1MessageContainer.h"
#include "PlmnId.h"
#include "TransferReason.h"
#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Data within a UE Context Transfer Request to start transferring of an
/// individual ueContext resource from old AMF to new AMF
/// </summary>
class UeContextTransferReqData {
public:
  UeContextTransferReqData();
  virtual ~UeContextTransferReqData();

  void validate();

  /////////////////////////////////////////////
  /// UeContextTransferReqData members

  /// <summary>
  ///
  /// </summary>
  TransferReason getReason() const;
  void setReason(TransferReason const &value);
  /// <summary>
  ///
  /// </summary>
  AccessType getAccessType() const;
  void setAccessType(AccessType const &value);
  /// <summary>
  ///
  /// </summary>
  PlmnId getPlmnId() const;
  void setPlmnId(PlmnId const &value);
  bool plmnIdIsSet() const;
  void unsetPlmnId();
  /// <summary>
  ///
  /// </summary>
  N1MessageContainer getRegRequest() const;
  void setRegRequest(N1MessageContainer const &value);
  bool regRequestIsSet() const;
  void unsetRegRequest();
  /// <summary>
  /// A string used to indicate the features supported by an API that is used as
  /// defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a
  /// bitmask indicating supported features in hexadecimal representation Each
  /// character in the string shall take a value of \&quot;0\&quot; to
  /// \&quot;9\&quot;, \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to
  /// \&quot;F\&quot; and shall represent the support of 4 features as described
  /// in table 5.2.2-3. The most significant character representing the
  /// highest-numbered features shall appear first in the string, and the
  /// character representing features 1 to 4 shall appear last in the string.
  /// The list of features and their numbering (starting with 1) are defined
  /// separately for each API. If the string contains a lower number of
  /// characters than there are defined features for an API, all features that
  /// would be represented by characters that are not present in the string are
  /// not supported
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const &value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();

  friend void to_json(nlohmann::json &j, const UeContextTransferReqData &o);
  friend void from_json(const nlohmann::json &j, UeContextTransferReqData &o);

protected:
  TransferReason m_Reason;

  AccessType m_AccessType;

  PlmnId m_PlmnId;
  bool m_PlmnIdIsSet;
  N1MessageContainer m_RegRequest;
  bool m_RegRequestIsSet;
  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* UeContextTransferReqData_H_ */
