/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UeContextTransferRspData.h
 *
 * Data within a successful response to the UE Context Transfer request
 */

#ifndef UeContextTransferRspData_H_
#define UeContextTransferRspData_H_

#include "N2InfoContent.h"
#include "UeContext.h"
#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Data within a successful response to the UE Context Transfer request
/// </summary>
class UeContextTransferRspData {
public:
  UeContextTransferRspData();
  virtual ~UeContextTransferRspData();

  void validate();

  /////////////////////////////////////////////
  /// UeContextTransferRspData members

  /// <summary>
  ///
  /// </summary>
  UeContext getUeContext() const;
  void setUeContext(UeContext const &value);
  /// <summary>
  ///
  /// </summary>
  N2InfoContent getUeRadioCapability() const;
  void setUeRadioCapability(N2InfoContent const &value);
  bool ueRadioCapabilityIsSet() const;
  void unsetUeRadioCapability();
  /// <summary>
  ///
  /// </summary>
  N2InfoContent getUeNbiotRadioCapability() const;
  void setUeNbiotRadioCapability(N2InfoContent const &value);
  bool ueNbiotRadioCapabilityIsSet() const;
  void unsetUeNbiotRadioCapability();
  /// <summary>
  /// A string used to indicate the features supported by an API that is used as
  /// defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a
  /// bitmask indicating supported features in hexadecimal representation Each
  /// character in the string shall take a value of \&quot;0\&quot; to
  /// \&quot;9\&quot;, \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to
  /// \&quot;F\&quot; and shall represent the support of 4 features as described
  /// in table 5.2.2-3. The most significant character representing the
  /// highest-numbered features shall appear first in the string, and the
  /// character representing features 1 to 4 shall appear last in the string.
  /// The list of features and their numbering (starting with 1) are defined
  /// separately for each API. If the string contains a lower number of
  /// characters than there are defined features for an API, all features that
  /// would be represented by characters that are not present in the string are
  /// not supported
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const &value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();

  friend void to_json(nlohmann::json &j, const UeContextTransferRspData &o);
  friend void from_json(const nlohmann::json &j, UeContextTransferRspData &o);

protected:
  UeContext m_UeContext;

  N2InfoContent m_UeRadioCapability;
  bool m_UeRadioCapabilityIsSet;
  N2InfoContent m_UeNbiotRadioCapability;
  bool m_UeNbiotRadioCapabilityIsSet;
  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* UeContextTransferRspData_H_ */
