/**
 * LMF Location
 * LMF Location Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UeConnectivityState.h
 *
 * Indicates the connectivity state of a UE.
 */

#ifndef UeConnectivityState_H_
#define UeConnectivityState_H_

#include "AccessType.h"
#include "CmState.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Indicates the connectivity state of a UE.
/// </summary>
class UeConnectivityState {
public:
  UeConnectivityState();
  virtual ~UeConnectivityState();

  void validate();

  /////////////////////////////////////////////
  /// UeConnectivityState members

  /// <summary>
  ///
  /// </summary>
  AccessType getAccessType() const;
  void setAccessType(AccessType const &value);
  /// <summary>
  ///
  /// </summary>
  CmState getConnectivitystate() const;
  void setConnectivitystate(CmState const &value);
  bool connectivitystateIsSet() const;
  void unsetConnectivitystate();

  friend void to_json(nlohmann::json &j, const UeConnectivityState &o);
  friend void from_json(const nlohmann::json &j, UeConnectivityState &o);

protected:
  AccessType m_AccessType;

  CmState m_Connectivitystate;
  bool m_ConnectivitystateIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* UeConnectivityState_H_ */
