/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UlclBpInformation.h
 *
 * UL CL or BP Information
 */

#ifndef UlclBpInformation_H_
#define UlclBpInformation_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// UL CL or BP Information
/// </summary>
class UlclBpInformation {
public:
  UlclBpInformation();
  virtual ~UlclBpInformation();

  void validate();

  /////////////////////////////////////////////
  /// UlclBpInformation members

  /// <summary>
  /// String uniquely identifying a NF instance. The format of the NF Instance
  /// ID shall be a Universally Unique Identifier (UUID) version 4, as described
  /// in IETF RFC 4122.
  /// </summary>
  std::string getUlclBpUpfId() const;
  void setUlclBpUpfId(std::string const &value);
  bool ulclBpUpfIdIsSet() const;
  void unsetUlclBpUpfId();

  friend void to_json(nlohmann::json &j, const UlclBpInformation &o);
  friend void from_json(const nlohmann::json &j, UlclBpInformation &o);

protected:
  std::string m_UlclBpUpfId;
  bool m_UlclBpUpfIdIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* UlclBpInformation_H_ */
