/**
 * NRF NFManagement Service
 * NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UPInterfaceType.h
 *
 * Types of User-Plane interfaces of the UPF
 */

#ifndef UPInterfaceType_H_
#define UPInterfaceType_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Types of User-Plane interfaces of the UPF
/// </summary>
class UPInterfaceType {
public:
  UPInterfaceType();
  virtual ~UPInterfaceType();

  void validate();

  /////////////////////////////////////////////
  /// UPInterfaceType members

  friend void to_json(nlohmann::json &j, const UPInterfaceType &o);
  friend void from_json(const nlohmann::json &j, UPInterfaceType &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* UPInterfaceType_H_ */
