/**
 * LMF Location
 * LMF Location Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * VelocityRequested.h
 *
 * Indicates velocity requirement.
 */

#ifndef VelocityRequested_H_
#define VelocityRequested_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Indicates velocity requirement.
/// </summary>
class VelocityRequested {
public:
  VelocityRequested();
  virtual ~VelocityRequested();

  void validate();

  /////////////////////////////////////////////
  /// VelocityRequested members

  friend void to_json(nlohmann::json &j, const VelocityRequested &o);
  friend void from_json(const nlohmann::json &j, VelocityRequested &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* VelocityRequested_H_ */
