/**
 * VAE_HDMapDynamicInfo
 * API for VAE HDMapDynamicInfo Service © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * HdmapDynamicinfoSubscriptionsCollectionDocumentApi.h
 *
 *
 */

#ifndef HdmapDynamicinfoSubscriptionsCollectionDocumentApi_H_
#define HdmapDynamicinfoSubscriptionsCollectionDocumentApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "HdMapDynamicInfoData.h"
#include "ProblemDetails.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class HdmapDynamicinfoSubscriptionsCollectionDocumentApi {
public:
  HdmapDynamicinfoSubscriptionsCollectionDocumentApi(
      std::shared_ptr<Pistache::Rest::Router>);
  virtual ~HdmapDynamicinfoSubscriptionsCollectionDocumentApi() {}
  void init();

  const std::string base = "/vae-hdmap-dynamic-info/v1";

private:
  void setupRoutes();

  void create_handler(const Pistache::Rest::Request &request,
                      Pistache::Http::ResponseWriter response);
  void hdmap_dynamicinfo_subscriptions_collection_document_api_default_handler(
      const Pistache::Rest::Request &request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// VAE_HDMapDynamicInfo resource create service Operation
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="hdMapDynamicInfoData"></param>
  virtual void create(const HdMapDynamicInfoData &hdMapDynamicInfoData,
                      Pistache::Http::ResponseWriter &response) = 0;
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* HdmapDynamicinfoSubscriptionsCollectionDocumentApi_H_ */
