/**
 * Unified Data Repository Service API file for Application Data
 * The API version is defined in 3GPP TS 29.504 © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: -
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * IndividualServiceParameterDataDocumentApi.h
 *
 *
 */

#ifndef IndividualServiceParameterDataDocumentApi_H_
#define IndividualServiceParameterDataDocumentApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "ProblemDetails.h"
#include "ServiceParameterData.h"
#include "ServiceParameterDataPatch.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class IndividualServiceParameterDataDocumentApi {
public:
  IndividualServiceParameterDataDocumentApi(
      std::shared_ptr<Pistache::Rest::Router>);
  virtual ~IndividualServiceParameterDataDocumentApi() {}
  void init();

  const std::string base = "";

private:
  void setupRoutes();

  void create_or_replace_service_parameter_data_handler(
      const Pistache::Rest::Request &request,
      Pistache::Http::ResponseWriter response);
  void delete_individual_service_parameter_data_handler(
      const Pistache::Rest::Request &request,
      Pistache::Http::ResponseWriter response);
  void update_individual_service_parameter_data_handler(
      const Pistache::Rest::Request &request,
      Pistache::Http::ResponseWriter response);
  void individual_service_parameter_data_document_api_default_handler(
      const Pistache::Rest::Request &request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Create or update an individual Service Parameter Data resource
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="serviceParamId">The Identifier of an Individual Service
  /// Parameter Data to be created or updated. It shall apply the format of Data
  /// type string.</param> <param name="serviceParameterData"></param>
  virtual void create_or_replace_service_parameter_data(
      const std::string &serviceParamId,
      const ServiceParameterData &serviceParameterData,
      Pistache::Http::ResponseWriter &response) = 0;

  /// <summary>
  /// Delete an individual Service Parameter Data resource
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="serviceParamId">The Identifier of an Individual Service
  /// Parameter Data to be updated. It shall apply the format of Data type
  /// string.</param>
  virtual void delete_individual_service_parameter_data(
      const std::string &serviceParamId,
      Pistache::Http::ResponseWriter &response) = 0;

  /// <summary>
  /// Modify part of the properties of an individual Service Parameter Data
  /// resource
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="serviceParamId">The Identifier of an Individual Service
  /// Parameter Data to be updated. It shall apply the format of Data type
  /// string.</param> <param name="serviceParameterDataPatch"></param>
  virtual void update_individual_service_parameter_data(
      const std::string &serviceParamId,
      const ServiceParameterDataPatch &serviceParameterDataPatch,
      Pistache::Http::ResponseWriter &response) = 0;
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* IndividualServiceParameterDataDocumentApi_H_ */
