/**
 * Npcf_AMPolicyAuthorization Service API
 * PCF Access and Mobility Policy Authorization Service. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * IndividualApplicationAMContextDocumentApi.h
 *
 *
 */

#ifndef IndividualApplicationAMContextDocumentApi_H_
#define IndividualApplicationAMContextDocumentApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "AppAmContextData.h"
#include "AppAmContextRespData.h"
#include "AppAmContextUpdateData.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class IndividualApplicationAMContextDocumentApi {
public:
  IndividualApplicationAMContextDocumentApi(
      std::shared_ptr<Pistache::Rest::Router>);
  virtual ~IndividualApplicationAMContextDocumentApi() {}
  void init();

  const std::string base = "/npcf-am-policyauthorization/v1";

private:
  void setupRoutes();

  void delete_app_am_context_handler(const Pistache::Rest::Request &request,
                                     Pistache::Http::ResponseWriter response);
  void get_app_am_context_handler(const Pistache::Rest::Request &request,
                                  Pistache::Http::ResponseWriter response);
  void mod_app_am_context_handler(const Pistache::Rest::Request &request,
                                  Pistache::Http::ResponseWriter response);
  void individual_application_am_context_document_api_default_handler(
      const Pistache::Rest::Request &request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Deletes an existing Individual Application AM Context
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="appAmContextId">string identifying the Individual Application
  /// AM Context resource</param>
  virtual void
  delete_app_am_context(const std::string &appAmContextId,
                        Pistache::Http::ResponseWriter &response) = 0;

  /// <summary>
  /// Reads an existing Individual Application AM Context
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="appAmContextId">string identifying the resource</param>
  virtual void get_app_am_context(const std::string &appAmContextId,
                                  Pistache::Http::ResponseWriter &response) = 0;

  /// <summary>
  /// Modifies an existing Individual Application AM Context
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="appAmContextId">string identifying the resource</param>
  /// <param name="appAmContextUpdateData">modification of the resource.</param>
  virtual void
  mod_app_am_context(const std::string &appAmContextId,
                     const AppAmContextUpdateData &appAmContextUpdateData,
                     Pistache::Http::ResponseWriter &response) = 0;
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* IndividualApplicationAMContextDocumentApi_H_ */
