/**
 * Unified Data Repository Service API file for subscription data
 * Unified Data Repository Service (subscription data). The API version is
 * defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: -
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Modify5GVnGroupApi.h
 *
 *
 */

#ifndef Modify5GVnGroupApi_H_
#define Modify5GVnGroupApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "PatchItem.h"
#include "PatchResult.h"
#include "ProblemDetails.h"
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class Modify5GVnGroupApi {
public:
  Modify5GVnGroupApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~Modify5GVnGroupApi() {}
  void init();

  const std::string base = "";

private:
  void setupRoutes();

  void modify5_g_vn_group_handler(const Pistache::Rest::Request &request,
                                  Pistache::Http::ResponseWriter response);
  void modify5_g_vn_group_api_default_handler(
      const Pistache::Rest::Request &request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// modify the 5GVnGroup
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="externalGroupId"></param>
  /// <param name="patchItem"></param>
  /// <param name="supportedFeatures">Features required to be supported by the
  /// target NF (optional, default to &quot;&quot;)</param>
  virtual void
  modify5_g_vn_group(const std::string &externalGroupId,
                     const std::vector<PatchItem> &patchItem,
                     const Pistache::Optional<std::string> &supportedFeatures,
                     Pistache::Http::ResponseWriter &response) = 0;
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* Modify5GVnGroupApi_H_ */
