/**
 * Nudsf_Timer
 * Nudsf Timer Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TimersDeleteApi.h
 *
 *
 */

#ifndef TimersDeleteApi_H_
#define TimersDeleteApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "NullValue.h"
#include "ProblemDetails.h"
#include "SearchExpression.h"
#include "TimerIdList.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class TimersDeleteApi {
public:
  TimersDeleteApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~TimersDeleteApi() {}
  void init();

  const std::string base = "/nudsf-timer/v1";

private:
  void setupRoutes();

  void delete_timers_handler(const Pistache::Rest::Request &request,
                             Pistache::Http::ResponseWriter response);
  void
  timers_delete_api_default_handler(const Pistache::Rest::Request &request,
                                    Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Delete one or multiple timers based on filter
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="realmId">Identifier(name) of the Realm</param>
  /// <param name="storageId">Identifier of the Storage</param>
  /// <param name="supportedFeatures">Features required to be supported by the
  /// target NF (optional, default to &quot;&quot;)</param> <param
  /// name="filter">A filter that determines the set of timers to be deleted
  /// (optional, default to SearchExpression())</param> <param
  /// name="expiredFilter">Presence indicates that only expired timers are to be
  /// deleted. (optional, default to NullValue())</param>
  virtual void
  delete_timers(const std::string &realmId, const std::string &storageId,
                const Pistache::Optional<std::string> &supportedFeatures,
                const Pistache::Optional<SearchExpression> &filter,
                const Pistache::Optional<NullValue> &expiredFilter,
                Pistache::Http::ResponseWriter &response) = 0;
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* TimersDeleteApi_H_ */
