/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * ApplicationSessionsCollectionApiImpl.h
 *
 *
 */

#ifndef APPLICATION_SESSIONS_COLLECTION_API_IMPL_H_
#define APPLICATION_SESSIONS_COLLECTION_API_IMPL_H_

#include <memory>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <ApplicationSessionsCollectionApi.h>

#include <pistache/optional.h>

#include "AppSessionContext.h"
#include "ExtendedProblemDetails.h"
#include "ProblemDetails.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class ApplicationSessionsCollectionApiImpl
    : public org::openapitools::server::api::ApplicationSessionsCollectionApi {
public:
  ApplicationSessionsCollectionApiImpl(std::shared_ptr<Pistache::Rest::Router>);
  ~ApplicationSessionsCollectionApiImpl() {}

  void post_app_sessions(const AppSessionContext &appSessionContext,
                         Pistache::Http::ResponseWriter &response);
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif