/**
 * Nudsf_DataRepository
 * Nudsf Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * BlockCRUDApiImpl.h
 *
 *
 */

#ifndef BLOCK_CRUD_API_IMPL_H_
#define BLOCK_CRUD_API_IMPL_H_

#include <memory>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <BlockCRUDApi.h>

#include <pistache/optional.h>

#include "AnyType.h"
#include "Inline_response_200.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class BlockCRUDApiImpl : public org::openapitools::server::api::BlockCRUDApi {
public:
  BlockCRUDApiImpl(std::shared_ptr<Pistache::Rest::Router>);
  ~BlockCRUDApiImpl() {}

  void create_or_modify_block(
      const std::string &realmId, const std::string &storageId,
      const std::string &recordId, const std::string &blockId,
      const AnyType &body, const Pistache::Optional<bool> &getPrevious,
      const Pistache::Optional<Pistache::Http::Header::Raw> &ifNoneMatch,
      const Pistache::Optional<Pistache::Http::Header::Raw> &ifMatch,
      const Pistache::Optional<std::string> &supportedFeatures,
      Pistache::Http::ResponseWriter &response);
  void
  delete_block(const std::string &realmId, const std::string &storageId,
               const std::string &recordId, const std::string &blockId,
               const Pistache::Optional<bool> &getPrevious,
               const Pistache::Optional<Pistache::Http::Header::Raw> &ifMatch,
               const Pistache::Optional<std::string> &supportedFeatures,
               Pistache::Http::ResponseWriter &response);
  void get_block(
      const std::string &realmId, const std::string &storageId,
      const std::string &recordId, const std::string &blockId,
      const Pistache::Optional<Pistache::Http::Header::Raw> &ifNoneMatch,
      const Pistache::Optional<Pistache::Http::Header::Raw> &ifModifiedSince,
      const Pistache::Optional<std::string> &supportedFeatures,
      Pistache::Http::ResponseWriter &response);
  void get_block_list(const std::string &realmId, const std::string &storageId,
                      const std::string &recordId,
                      const Pistache::Optional<std::string> &supportedFeatures,
                      Pistache::Http::ResponseWriter &response);
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif