/**
 * LMF Location
 * LMF Location Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * CancelLocationApiImpl.h
 *
 *
 */

#ifndef CANCEL_LOCATION_API_IMPL_H_
#define CANCEL_LOCATION_API_IMPL_H_

#include <memory>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <CancelLocationApi.h>

#include <pistache/optional.h>

#include "CancelLocData.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class CancelLocationApiImpl
    : public org::openapitools::server::api::CancelLocationApi {
public:
  CancelLocationApiImpl(std::shared_ptr<Pistache::Rest::Router>);
  ~CancelLocationApiImpl() {}

  void cancel_location(const CancelLocData &cancelLocData,
                       Pistache::Http::ResponseWriter &response);
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif