/**
 * 3gpp-network-parameter-configuration
 * API for network parameter configuration. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NpConfigurationAPIConfigurationLevelPUTOperationApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

NpConfigurationAPIConfigurationLevelPUTOperationApiImpl::
    NpConfigurationAPIConfigurationLevelPUTOperationApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr)
    : NpConfigurationAPIConfigurationLevelPUTOperationApi(rtr) {}

void NpConfigurationAPIConfigurationLevelPUTOperationApiImpl::
    scs_as_id_configurations_configuration_id_put(
        const std::string &scsAsId, const std::string &configurationId,
        const NpConfiguration &npConfiguration,
        Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org
