/**
 * Unified Data Repository Service API file for policy data
 * The API version is defined in 3GPP TS 29.504 © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: -
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * PolicyDataForIndividualUeDocumentApiImpl.h
 *
 *
 */

#ifndef POLICY_DATA_FOR_INDIVIDUAL_UE_DOCUMENT_API_IMPL_H_
#define POLICY_DATA_FOR_INDIVIDUAL_UE_DOCUMENT_API_IMPL_H_

#include <memory>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <PolicyDataForIndividualUeDocumentApi.h>

#include <pistache/optional.h>

#include "PolicyDataForIndividualUe.h"
#include "PolicyDataSubset.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class PolicyDataForIndividualUeDocumentApiImpl
    : public org::openapitools::server::api::
          PolicyDataForIndividualUeDocumentApi {
public:
  PolicyDataForIndividualUeDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>);
  ~PolicyDataForIndividualUeDocumentApiImpl() {}

  void read_policy_data(
      const std::string &ueId, const Pistache::Optional<std::string> &suppFeat,
      const Pistache::Optional<std::vector<PolicyDataSubset>> &dataSubsetNames,
      Pistache::Http::ResponseWriter &response);
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif