/**
 * Nudm_MT
 * UDM MT Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI,
 * TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * ProvideUELocationApiImpl.h
 *
 *
 */

#ifndef PROVIDE_UE_LOCATION_API_IMPL_H_
#define PROVIDE_UE_LOCATION_API_IMPL_H_

#include <memory>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <ProvideUELocationApi.h>

#include <pistache/optional.h>

#include "LocationInfoRequest.h"
#include "LocationInfoResult.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class ProvideUELocationApiImpl
    : public org::openapitools::server::api::ProvideUELocationApi {
public:
  ProvideUELocationApiImpl(std::shared_ptr<Pistache::Rest::Router>);
  ~ProvideUELocationApiImpl() {}

  void provide_location_info(const std::string &supi,
                             const LocationInfoRequest &locationInfoRequest,
                             Pistache::Http::ResponseWriter &response);
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif