/**
 * Nhss_imsUECM
 * Nhss UE Context Management Service for IMS. © 2021, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SCSCFRestorationInfoRetrievalApiImpl.h
 *
 *
 */

#ifndef SCSCF_RESTORATION_INFO_RETRIEVAL_API_IMPL_H_
#define SCSCF_RESTORATION_INFO_RETRIEVAL_API_IMPL_H_

#include <memory>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <SCSCFRestorationInfoRetrievalApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include "ScscfRestorationInfoResponse.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class SCSCFRestorationInfoRetrievalApiImpl
    : public org::openapitools::server::api::SCSCFRestorationInfoRetrievalApi {
public:
  SCSCFRestorationInfoRetrievalApiImpl(std::shared_ptr<Pistache::Rest::Router>);
  ~SCSCFRestorationInfoRetrievalApiImpl() {}

  void get_scscf_restoration_info(const std::string &impu,
                                  Pistache::Http::ResponseWriter &response);
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif