/**
 * 3gpp-time-sync-exposure
 * API for time synchronization exposure. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * TimeSynchronizationExposureSubscriptionsApiImpl.h
 *
 *
 */

#ifndef TIME_SYNCHRONIZATION_EXPOSURE_SUBSCRIPTIONS_API_IMPL_H_
#define TIME_SYNCHRONIZATION_EXPOSURE_SUBSCRIPTIONS_API_IMPL_H_

#include <memory>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <TimeSynchronizationExposureSubscriptionsApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "TimeSyncExposureSubsc.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class TimeSynchronizationExposureSubscriptionsApiImpl
    : public org::openapitools::server::api::
          TimeSynchronizationExposureSubscriptionsApi {
public:
  TimeSynchronizationExposureSubscriptionsApiImpl(
      std::shared_ptr<Pistache::Rest::Router>);
  ~TimeSynchronizationExposureSubscriptionsApiImpl() {}

  void af_id_subscriptions_get(const std::string &afId,
                               Pistache::Http::ResponseWriter &response);
  void
  af_id_subscriptions_post(const std::string &afId,
                           const TimeSyncExposureSubsc &timeSyncExposureSubsc,
                           Pistache::Http::ResponseWriter &response);
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif